### ISSUE TITLE
more robust detection of installed backends

### ISSUE THREAD

**Issue by stevengj** [stevengj/PyPlot.jl#10]
Currently, if PyPlot uses PyCall's `pygui()`, it lets `pygui()` pick the first supported toolkit that is installed for Python.  However, if the toolkit was installed _after_ matplotlib, it looks like matplotlib may need to be rebuilt in order to include that toolkit's backend.

For example, now that PyCall has switched its default GUI to Qt rather than wx, @bkalpert reported the following error:

```
julia> using PyPlot
ERROR: PyError (PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named backend_qt4agg',)
 File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
   _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
 File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
   globals(),locals(),[backend_name])

in pyerr_check at /home/alpert/.julia/PyCall/src/exception.jl:58
in pyimport at /home/alpert/.julia/PyCall/src/PyCall.jl:85
in include_from_node1 at loading.jl:92
in reload_path at loading.jl:117
in require at loading.jl:48
at /home/alpert/.julia/PyPlot/src/PyPlot.jl:49
```

**Comment by dtcitron** [comment]
I just got back around to trying to work with PyPlot in Julia, and it works
perfectly now!  Thanks!

On Fri, Nov 7, 2014 at 10:06 PM, Steven G. Johnson <notifications@github.com

**Comment by stevengj** [comment]
Great!
