### ISSUE TITLE
PyPlot fails to show plot when Julia is compiled with Intel MKL

### ISSUE THREAD

**Issue by jdtuck** [stevengj/PyPlot.jl#100]
When I try to run a simple plot

```
using Pyplot
plot(linspace(0,1,100))
```

The REPL seg faults with
mkl_blas_avx2_xdcopy at /opt/intel/composerxe/mkl/lib/intel64/libmkl_avx2.so (unknown line)
Segmentation fault (core dumped)

Ideas?

**Comment by marius311** [comment]
I think I'm running into essentially the same thing, 

```
julia> using PyPlot

julia> plot([1,2,3])

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
mkl_blas_avx2_dgemm_kernel_nocopy_NN_b0 at /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_avx2.so (unknown line)
Allocations: 5542910 (Pool: 5541409; Big: 1501); GC: 10
Segmentation fault (core dumped)
```

I do indeed have Julia compiled with Intel but Numpy with Gnu. Would anyone happen to have any ideas for a workaround without having to recompile Numpy with Intel ?
