### ISSUE TITLE
PyPlot+ProfileView = segfault

### ISSUE THREAD

**Issue by few** [stevengj/PyPlot.jl#104]
The following command reliably crashes julia. Note that PyPlot and ProfileView alone work fine. It's just the combination that crashes. Filing this as issue for PyPlot because the first error mentions python.

$ LC_ALL=C ./julia-debug -P 'using PyPlot; using ProfileView; plot(1,1)'
INFO: Loading help data...
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-11-23 20:19 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> Fatal Python error: PyEval_RestoreThread: NULL tstate

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 637627390)
PyEval_RestoreThread at /usr/lib/x86_64-linux-gnu/libpython2.7.so (unknown line)
unknown function (ip: 574983891)
TclInvokeStringCommand at /usr/lib/x86_64-linux-gnu/libtcl8.6.so (unknown line)
TclNRRunCallbacks at /usr/lib/x86_64-linux-gnu/libtcl8.6.so (unknown line)
unknown function (ip: 567939855)
Tcl_EvalEx at /usr/lib/x86_64-linux-gnu/libtcl8.6.so (unknown line)
Tk_BindEvent at /usr/lib/x86_64-linux-gnu/libtk8.6.so (unknown line)
TkBindEventProc at /usr/lib/x86_64-linux-gnu/libtk8.6.so (unknown line)
Tk_HandleEvent at /usr/lib/x86_64-linux-gnu/libtk8.6.so (unknown line)
unknown function (ip: 571738720)
Tcl_ServiceEvent at /usr/lib/x86_64-linux-gnu/libtcl8.6.so (unknown line)
Tcl_DoOneEvent at /usr/lib/x86_64-linux-gnu/libtcl8.6.so (unknown line)
tcl_doevent at /home/luther/.julia/v0.3/Tk/src/tkwidget.jl:20
tcl_doevent at /home/luther/.julia/v0.3/Tk/src/tkwidget.jl:20
jlcall_tcl_doevent;20847 at  (unknown line)
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
_uv_hook_asynccb at stream.jl:489
jlcall__uv_hook_asynccb;20719 at  (unknown line)
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 921521335)
unknown function (ip: 921523302)
jl_uv_asynccb at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
uv__run_timers at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
uv_run at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
jl_run_once at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
process_events at ./stream.jl:537
wait at ./task.jl:274
wait at ./task.jl:194
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
stream_wait at stream.jl:263
wait_readnb at stream.jl:316
read at stream.jl:698
read at io.jl:133
jlcall_read;20902 at  (unknown line)
unknown function (ip: 920933759)
jl_trampoline at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
anonymous at LineEdit.jl:859
unknown function (ip: 920933759)
jl_trampoline at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
prompt! at ./LineEdit.jl:1399
run_interface at ./LineEdit.jl:1374
run_interface_3B_1865 at /home/luther/software/julia0.3/usr/bin/../lib/julia/sys.so (unknown line)
unknown function (ip: 920933759)
jl_trampoline at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
run_frontend at ./REPL.jl:818
run_repl at ./REPL.jl:169
unknown function (ip: 920933759)
jl_trampoline at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
_start at ./client.jl:399
_start_3B_1729 at /home/luther/software/julia0.3/usr/bin/../lib/julia/sys.so (unknown line)
unknown function (ip: 920933759)
jl_trampoline at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 920894362)
jl_apply_generic at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 4199848)
unknown function (ip: 4202869)
julia_trampoline at /home/luther/software/julia0.3/usr/bin/../lib/libjulia-debug.so (unknown line)
unknown function (ip: 4203350)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199593)
unknown function (ip: 0)

versioninfo(true)
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
DEBUG build
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
           Ubuntu 14.04.1 LTS
  uname: Linux 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64
Memory: 7.679298400878906 GB (451.6640625 MB free)
Uptime: 220181.0 sec
Load Avg:  0.53466796875  0.32958984375  0.2578125
Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz: 
       speed         user         nice          sys         idle          irq
#1   800 MHz     454831 s       2468 s      80958 s    6890345 s          3 s
#2   800 MHz     495600 s       1113 s      66488 s    1075645 s          0 s
#3  3201 MHz     592704 s        905 s     116209 s    1087325 s          0 s
#4   800 MHz     412495 s       1184 s      45971 s    1083339 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = xterm
  XDG_SESSION_PATH = /org/freedesktop/DisplayManager/Session0
  XDG_SEAT_PATH = /org/freedesktop/DisplayManager/Seat0
  DEFAULTS_PATH = /usr/share/gconf/ubuntu.default.path
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  MANDATORY_PATH = /usr/share/gconf/ubuntu.mandatory.path
  HOME = /home/luther
  COMPIZ_BIN_PATH = /usr/bin/

Package Directory: /home/luther/.julia/v0.3
3 required packages:
 - ProfileView                   0.0.7
 - PyPlot                        1.4.3
 - Winston                       0.11.6
23 additional packages:
 - ArrayViews                    0.4.8
 - BinDeps                       0.3.6
 - Cairo                         0.2.20
 - Color                         0.3.13
 - Compat                        0.2.2
 - Distance                      0.5.0
 - Distances                     0.2.0
 - FixedPointNumbers             0.0.4
 - ImageView                     0.1.8
 - Images                        0.4.22
 - IniFile                       0.2.4
 - LaTeXStrings                  0.1.2
 - NearestNeighbors              0.0.0-             master (unregistered)
 - PyCall                        0.6.2
 - SHA                           0.0.3
 - SIUnits                       0.0.2
 - SmoothingKernels              0.0.0
 - StatsBase                     0.6.10
 - TexExtensions                 0.0.2
 - Tk                            0.2.16
 - URIParser                     0.0.3
 - Zlib                          0.1.7
 - kNN                           0.0.0+             master

**Comment by cberzan** [comment]
I'm seeing this issue as well. The plot window appears, but julia crashes as soon as I try to move my mouse over the plot window. Using `using PyPlot; import ProfileView` did not help. Is there anything else I can do to debug this?

**Comment by cberzan** [comment]
I suspect the problem is because both PyPlot and ProfileView are trying to run their own Tk event loops. I was able to work around this issue by switching PyPlot to use a non-tk backend:

```
using PyCall
pygui(:qt)
using PyPlot
plot(1,1)
using ProfileView
@profile ...
ProfileView.view()
```

This lets me interact with both the matplotlib window and the ProfileView window without any crashes.

**Comment by stevengj** [comment]
Ah, yes, that would do it.  I doubt there's any reasonable way around it other than to use separate backends.
