### ISSUE TITLE
PyPlot not initializing; pltm not defined

### ISSUE THREAD

**Issue by ghost** [stevengj/PyPlot.jl#108]
Typing 

Pkg.add("PyPlot")
using PyPlot

from julia 0.3.3 results in:
[[
Warning: error initializing module PyPlot:
PyCall.PyError(msg=":PyImport_ImportModule", T=PyCall.PyObject(o=0x0000000043382540), val=PyCall.PyObject(o=0x000000003f48dab8), traceback=PyCall.PyObject(o=0x000000003e91bef0))
]](delimiters [[ ]] added)

When trying to run

@pyimport matplotlib.pyplot as plt

The result is:
[[
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('cannot import name scimath',)
  File "/usr/lib64/python2.7/site-packages/matplotlib/**init**.py", line 179, in <module>
    from matplotlib.cbook import is_string_like
  File "/usr/lib64/python2.7/site-packages/matplotlib/cbook.py", line 32, in <module>
    import numpy as np
  File "/usr/lib64/python2.7/site-packages/numpy/**init**.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib64/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python2.7/site-packages/numpy/lib/**init**.py", line 17, in <module>
    from . import scimath as emath

 in pyerr_check at /home/jdgallag/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /home/jdgallag/.julia/v0.3/PyCall/src/PyCall.jl:91
]]

What can be done?

**Comment by lkuper** [comment]
FWIW, I'm having a very similar issue with Julia 0.3.7 and a just-now-installed PyPlot:

```
lkuper@lkuper-u1404:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.7 (2015-03-23 21:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

julia> Pkg.add("PyPlot")
INFO: Initializing package repository /home/lkuper/.julia/v0.3
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of Color from git://github.com/JuliaLang/Color.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of FixedPointNumbers from git://github.com/JeffBezanson/FixedPointNumbers.jl.git
INFO: Cloning cache of Graphics from git://github.com/JuliaLang/Graphics.jl.git
INFO: Cloning cache of LaTeXStrings from git://github.com/stevengj/LaTeXStrings.jl.git
INFO: Cloning cache of PyCall from git://github.com/stevengj/PyCall.jl.git
INFO: Cloning cache of PyPlot from git://github.com/stevengj/PyPlot.jl.git
INFO: Installing Color v0.4.2
INFO: Installing Compat v0.3.6
INFO: Installing Dates v0.3.2
INFO: Installing FixedPointNumbers v0.0.6
INFO: Installing Graphics v0.1.0
INFO: Installing LaTeXStrings v0.1.2
INFO: Installing PyCall v0.7.4
INFO: Installing PyPlot v1.5.1
INFO: Package database updated

julia> using PyPlot
Warning: error initializing module PyPlot:
PyCall.PyError(msg=":PyImport_ImportModule", T=PyCall.PyObject(o=0x00000000ed2e41e0), val=PyCall.PyObject(o=0x00000000eca36200), traceback=PyCall.PyObject(o=0x0000000000000000))
```

**Comment by stevengj** [comment]
@lkuper, not all errors in initializing matplotlib have the same origin, unfortunately.   If we figure out a specific reason for yours it is likely to be a separate issue.  That takes some digging to find out specifically what module import is failing, I'm afraid.

For example, if you are using Ubuntu, I had a report recently that the Ubuntu Matplotlib is set up to support the GTK3 backend by default, but PyCall has not implemented the GTK3 event loops yet so it can't initialize properly for interactive use.   You can try `using PyCall; pygui(:qt); using PyPlot` to force it to use the Qt backend.

**Comment by lkuper** [comment]
@stevengj, I see, thanks.  Yes, this issue was on Ubuntu.

**Comment by vote539** [comment]
Confirming this issue in the Ubuntu release of Julia, which I just installed yesterday on Ubuntu 14.04 according to [the instructions on this page](http://julialang.org/downloads/platform.html#Ubuntu).  Rather than building from source I am experimenting with Gadfly for my plotting needs, which so far seems to be working.

**Comment by stevengj** [comment]
I think it should be straightforward to add gtk3 support to PyCall; I just don't have access to an Ubuntu machine at the moment.

**Comment by iagoba** [comment]
I use Julia on a Mac OS X, and I get the same error:
"""Warning: error initializing module PyPlot:
PyCall.PyError(msg=":PyImport_ImportModule", T=PyCall.PyObject(o=0x000000000b236e58), val=PyCall.PyObject(o=0x000000000b6743c8), traceback=PyCall.PyObject(o=0x0000000000000000))"""

I've installed PyPlot with no problem, Pkg.test("PyCall") passed.

**Comment by stevengj** [comment]
@iagoba, what happens if you `import matplotlib` in Python?

**Comment by iagoba** [comment]
@stevengj It works also just fine with one of the versions of python. More concretely the 3.4. I have also installed the 2.7 but no matplotlib for this.

`$ python3.4 -c 'import matplotlib; print(matplotlib.__version__, matplotlib.__file__)'
1.4.3 /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/__init__.py`
