### ISSUE TITLE
how to call a method on an Axes object?

### ISSUE THREAD

**Issue by cberzan** [stevengj/PyPlot.jl#109]
In Python, I can draw patches on the plot by calling `add_patch` on the `Axes` object:

```
import matplotlib.pyplot as plt
ax = plt.gca()
ax.add_patch(plt.Circle((1, 2), radius=3))
```

Is there any way to do this from Julia? I can do `ax = plt.gca()`, but `ax` is just a `PyObject` wrapper, and it doesn't have a method `add_patch`.

(AFAICT, there is no function in the top-level [pyplot API](http://matplotlib.org/api/pyplot_api.html) that adds an arbitrary patch.)

**Comment by cberzan** [comment]
Figured out a hacky way to do it:

```
PyCall.pycall(ax["add_patch"], PyCall.PyAny, plt.Circle((0.1, 0.1), radius=0.2))
```

It would be nice if this was documented, or if there was an easier way to do it, similar to how you're exporting the pyplot API functions.

Thanks for all the great work on PyCall & PyPlot :)

**Comment by stevengj** [comment]
```
using PyPlot
ax = gca()
ax[:add_patch](plt.Circle((0.1, 0.1), radius=0.2))
```
should work.  This is explained in the PyCall documentation; the basic difference from Python is that because `.` is not currently overloadable you have to use `foo[:bar]` instead of `foo.bar`.
