### ISSUE TITLE
hist not honoring the range parameter

### ISSUE THREAD

**Issue by nowozin** [stevengj/PyPlot.jl#113]
```julia
fig, axes = plt.subplots(figsize=(5.0,3.0))
axes[:hist](randn(1000); bins=100, range=[-10.0,10.0])
fig[:tight_layout]()
fig
```

Should produce a histogram ranging on the x-axis from -10 to 10, but does not.
The range argument does not seem to have any effect when using Julia/PyPlot.

**Comment by stevengj** [comment]
Works for me with Matplotlib 1.4.0 (see `PyPlot.version`).

**Comment by nowozin** [comment]
This does not work with version 1.3.1 on Ubuntu 14.10.

I upgraded using [these instructions](http://askubuntu.com/questions/366462/most-up-to-date-ipython-and-matplotlib-in-ubuntu-13-10) to matplotlib version 1.4.2, and now everything is working fine.

Thanks Steven!
