### ISSUE TITLE
any way to custom font in PyPlot?

### ISSUE THREAD

**Issue by retsyo** [stevengj/PyPlot.jl#114]
In order to display Chinese on the chart, I followed the instruction on http://blog.csdn.net/rumswell/article/details/6544377. But obviously, I failed. Any hints? Thanks
1)the first solution use dict in py, but how to translate it to Julia?
mpl.rcParams['font.sans-serif'] = ['SimHei'] 
plt.title(u'some Chinese here')  

2)the second one use font_manager, which I cannot find after "using PyPlot"
myfont = font_manager.FontProperties(fname='C:/Windows/Fonts/msyh.ttf')  
title(u'some Chinese here', fontproperties=myfont)

**Comment by stevengj** [comment]
```julia
PyCall.PyDict(matplotlib["rcParams"])["font.sans-serif"] = ["SimHei"]
title("some Chinese here")
```
Or, if you need to set the `rcParams` before initializing PyPlot:
```
using PyCall
PyDict(pyimport("matplotlib")["rcParams"])["font.sans-serif"] = ["Courier"]
using PyPlot
....plotting...
```
Or, for the second option:
```
matplotlib["font_manager"][:FontProperties](fname="C:/Windows/Fonts/msyh.ttf")
title("some Chinese here", fontproperties=myfont)
```

**Comment by nbecker** [comment]
I'm baffled, the 1st line works, but the 2nd gives an error
import PyCall
PyCall.PyDict(matplotlib["rcParams"])["font.family"] = ["STIXGeneral"]
PyCall.PyDict(matplotlib["rcParams"])["mathtext.fontset"] = ["stix"]

ERROR: LoadError: PyError (:PyObject_SetItem) <class 'TypeError'>
TypeError("unhashable type: 'list'",)
  File "/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/__init__.py", line 886, in __setitem__
    cval = self.validate[key](val)
  File "/home/nbecker/.local/lib/python3.5/site-packages/matplotlib/rcsetup.py", line 67, in __call__
    if s in self.valid:

 in pyerr_check at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/nbecker/.julia/v0.6/PyCall/src/exception.jl:79 [inlined]
 in setindex!(::PyCall.PyDict{PyCall.PyAny,PyCall.PyAny}, ::Array{String,1}, ::String) at /home/nbecker/.julia/v0.6/PyCall/src/conversions.jl:439
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 in macro expansion at ./REPL.jl:97 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:66
while loading /home/nbecker/interference/test_roc.jl, in expression starting on line 16

**Comment by stevengj** [comment]
You get exactly the same error in Python `>>> matplotlib.rcParams["mathtext.fontset"] = ['stix']` so I'm not sure why you think it should work in Julia...

Did you mean `PyCall.PyDict(matplotlib["rcParams"])["mathtext.fontset"] = "stix"`?

**Comment by nbecker** [comment]
yes, I had tried to blindly copy the previous example, but you are correct, I should write
import PyCall
PyCall.PyDict(matplotlib["rcParams"])["font.family"] = "STIXGeneral"
PyCall.PyDict(matplotlib["rcParams"])["mathtext.fontset"] = "stix"

**Comment by stevengj** [comment]
The example above was copied from [here](http://blog.csdn.net/rumswell/article/details/6544377), which used a list of strings in Python for `rcParams['font.sans-serif']`, since the default value of this is a list of strings.  Similarly, the default value of `matplotlib.rcParams["font.family"]` is also a list of strings (but I think if you use a single string then this is passed to the `list` constructor and it is okay).  In contrast, `matplotlib.rcParams["mathtext.fontset"]` defaults to a single string.

This doesn't seem to be very well [documented by matplotlib](http://matplotlib.org/users/customizing.html), but a good rule of thumb is to look at the type of the default value and then assign the parameter to something of the same (or analogous) type.

**Comment by emcangi** [comment]
This syntax still works for me in Julia 0.7 (PyPlot 2.8.1, PyCall 1.90.0):

`PyCall.PyDict(matplotlib["rcParams"])["font.sans-serif"] = ["myfavoritefont"]`

but I can't get it to work using the updated dot overloading:

`PyCall.PyDict(matplotlib.rcParams)["font.sans-serif"] = ["myfavoritefont"]` --> does not update the font, and plots revert to matplotlib defaults.

Is there something else I'm missing here? I read the section of the PyCall documentation about PyDict, but didn't glean what I need from it.

**Comment by stevengj** [comment]
Use `matplotlib."rcParams"` to get the unconverted Python object.
