### ISSUE TITLE
random InexactError() after multiple plots using IJulia

### ISSUE THREAD

**Issue by axsk** [stevengj/PyPlot.jl#119]
I use a loop to plot data and save it to files, using PyPlot's `plot`, `savefig`, and `close` functions in each iteration. 
The error happened after random iterations (3,11,6,8 so far).

``` julia 
LoadError: InexactError()
while loading In[89], in expression starting on line 2
 in getindex at ...\.julia\v0.4\PyCall\src\PyCall.jl:249 
 in pysequence_query at ...\.julia\v0.4\PyCall\src\conversions.jl:739 
 in convert at ...\.julia\v0.4\PyCall\src\conversions.jl:813 
 in pycall at ...\.julia\v0.4\PyCall\src\PyCall.jl:94 
 in fn at ...\.julia\v0.4\PyCall\src\conversions.jl:181 
 in close_queued_figs at ...\.julia\v0.4\PyPlot\src\PyPlot.jl:295
```

Unfortunately I don't know how to get a more detailed backtrace of the error, so I can't tell where it is happening exactly (IJulia/Windows issue?).

Edit:
I guess there is no longer backtrace as `close_queued_figs` is called as a IJulia hook, thus not called by my code.

**Comment by stevengj** [comment]
Can you give your sample code?

**Comment by axsk** [comment]
I can't even get the error now, so I guess it was something else then PyPlot..
Sorry for the noise :/
