### ISSUE TITLE
Performance issue after latest update

### ISSUE THREAD

**Issue by juliohm** [stevengj/PyPlot.jl#120]
For some reason plot commands became really slow in IJulia after I updated Python and Julia. Any idea on what is causing the issue?

```python
>>> import sys
>>> sys.version
'3.4.3 (default, Mar 25 2015, 17:13:50) \n[GCC 4.9.2 20150304 (prerelease)]'
```

```julia
julia> versioninfo()
Julia Version 0.4.0-dev+4059
Commit e0d95e9* (2015-03-29 15:28 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.status("PyPlot")
 - PyPlot                        1.5.1+             master

julia> Pkg.status("IJulia")
 - IJulia                        0.2.1+             master
```

**Comment by juliohm** [comment]
I tried `@time imshow(randn(400,400))` and it takes 0.06 seconds which is ok. The image however takes a while to show up in the notebook. The kernel is busy.

**Comment by stevengj** [comment]
Can you try doing a `Pkg.update()`?  I had accidentally broken the numpy wrappers in PyCall, so it was making a very inefficient copy of the array as nested Python lists rather than using NumPy.

**Comment by juliohm** [comment]
Hi Steven,

I did the update, but the problem persists.

**Comment by juliohm** [comment]
@stevengj this is probably an issue of IJulia instead of PyCall/PyPlot, no?

**Comment by stevengj** [comment]
@juliohm, that's true, but only if you didn't update PyCall/PyPlot when you updated IJulia.  Are you sure that isn't the case?

**Comment by juliohm** [comment]
Hi Steven,

I only updated IJulia after noticing the issue with imshow().

Do you want me to try with specific versions?

**Comment by stevengj** [comment]
@juliohm, you said that you had also updated Python?  What IPython version are you using?

**Comment by juliohm** [comment]
IPython 3.0.0 (Jupyter)

This is the root of the issue?

**Comment by stevengj** [comment]
Can you try it with IPython 2.x (but everything else the same) to see if the performance issue goes away?

**Comment by juliohm** [comment]
I cannot guarantee I'll have time to downgrade, but will try.

Thanks.

**Comment by juliohm** [comment]
Hi Steven, you don't have easy access to Jupyter?

-Júlio

**Comment by juliohm** [comment]
The issue is gone.

**Comment by stevengj** [comment]
Great!

**Comment by tomaskrehlik** [comment]
Hi Steven, I am getting this issue again. In short, plots show swiftly when I work from terminal, in IJulia, for complicated plots the slowdown is such that it is practically unusable. I work in this environment:
````
  | | |_| | | | (_| |  |  Version 0.4.1 (2015-11-08 10:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin15.0.0


julia> Pkg.status("IJulia")
 - IJulia                        1.1.8

julia> Pkg.status("PyPlot")
 - PyPlot                        2.1.1

julia> Pkg.status("PyCall")
 - PyCall                        1.2.0


You are using Jupyter notebook.

The version of the notebook server is 4.0.6-e7cffd3 and is running on:
Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
````
Tried to change to python 3.5, did not help.

I would be glad for any help on this.

**Comment by stevengj** [comment]
You haven't set `PyPlot.svg(true)`, have you?

**Comment by tomaskrehlik** [comment]
No, I haven't. Is there any way how to debug? I have today a bit of time so might try to do that.

**Comment by stevengj** [comment]
You could try to figure out if the backend is different in the terminal vs. IJulia.   Or try the `Agg` backend in the terminal and check that writing to a `.png` file is fast.  (IJulia uses the Agg backend for inline plots, and sends them as PNG.)

**Comment by tomaskrehlik** [comment]
Alright, it was probably my mistake. Because I don't know much `matplotlib` I was copypasting stuff and trying to get a decent image and I also copypasted
````
fig[:canvas][:draw]()
````
that causes the whole issue. Any reason why this exact line is causing so much trouble? Thanks anyway and sorry for bothering.

**Comment by stevengj** [comment]
No idea why that would be a problem, other than potentially causing things to be rendered twice.
