### ISSUE TITLE
Cannot set colorbar labels.

### ISSUE THREAD

**Issue by kzapfe** [stevengj/PyPlot.jl#123]
Hello stevengj:

First and most important: great package! It is fast and easier than matplotlib to use. 
But I cannot seem to understand the sintaxis for puting labels on the colorbars. I followed the examples on the matplotlib documentation and it throws errors at me. I cannot even seem to find the adecuate codeword for such a function. What I am missing here?

**Comment by stevengj** [comment]
This works, for example:
```
pcolor(rand(10,10))
cb = colorbar()
cb[:set_label]("some colors")
```
The biggest difference is that where you would write `foo.bar` in Python, you write `foo[:bar]` in Julia.  This is because Julia doesn't currently allow `.` to be overloaded.

**Comment by kzapfe** [comment]
Thanks! I was then struggling with sintaxis...
