### ISSUE TITLE
cannot access axes of fig,ax=subplots(n,m) on MacOS 10.9?

### ISSUE THREAD

**Issue by floswald** [stevengj/PyPlot.jl#124]
I'm a bit confused why I cannot replicate this example here (taken from http://quant-econ.net/jl/julia_libraries.html#plotting, and this was produced by @spencerlyon2 I think - maybe he can help?): I get a plot window that remains empty. If I change the example to the below, it works. Should I expect only the bottom version to work? The first example seems to allow for more flexilibility, that's all. My configuration is at the very end of the issue. I've just installed an up-to date version of matplotlib and numpy/scipy, so that can't be it I think.

```julia
using PyPlot
using Distributions

u = Uniform()

fig, ax = subplots()
x = linspace(-4, 4, 150)
for i in 1:3
    # == Compute normal pdf from randomly generated mean and std == #
    m, s = rand(u) * 2 - 1, rand(u) + 1
    d = Normal(m, s)
    y = pdf(d, x)
    # == Plot current pdf == #
    ax[:plot](x, y, linewidth=2, alpha=0.6, label="draw $i")
end
ax[:legend]()
```

that here works:

```julia
using PyPlot
using Distributions

u = Uniform()

x = linspace(-4, 4, 150)
for i in 1:3
    # == Compute normal pdf from randomly generated mean and std == #
    m, s = rand(u) * 2 - 1, rand(u) + 1
    d = Normal(m, s)
    y = pdf(d, x)
    # == Plot current pdf == #
    plot(x, y, linewidth=2, alpha=0.6, label="draw $i")
end
legend()
```

Setup:

```julia
julia> PyPlot.version
v"1.4.3"

julia> versioninfo()
Julia Version 0.3.6
Commit 0c24dca* (2015-02-17 22:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```

MAC OS 10.10.2 (14C109)

**Comment by floswald** [comment]
this may be just lack of understanding on my behalf of how the matplotlib API works - sorry. I found out that I can use the `:add_subplot` function to do what I want. not sure this is an issue after all.

```julia
julia> fig = figure()
Figure(PyObject <matplotlib.figure.Figure object at 0x10bd8a150>)

julia> fig[:add_subplot](2,1,1)
PyObject <matplotlib.axes._subplots.AxesSubplot object at 0x10be331d0>

julia> plot(1:10,rand(10))
1-element Array{Any,1}:
 PyObject <matplotlib.lines.Line2D object at 0x10d7bdbd0>

julia> fig[:add_subplot](2,1,2)
PyObject <matplotlib.axes._subplots.AxesSubplot object at 0x10be33350>

julia> plot(1:10,rand(10))
1-element Array{Any,1}:
 PyObject <matplotlib.lines.Line2D object at 0x10f34f410>

# now go back to the first subplot and do something to it: annotate.

julia> fig[:add_subplot](2,1,1)
PyObject <matplotlib.axes._subplots.AxesSubplot object at 0x10be331d0>

julia> annotate("subplot number 1!",xy=(6,0.8))
PyObject <matplotlib.text.Annotation object at 0x10f007c10>
```

**Comment by spencerlyon2** [comment]
@floswald glad you found a work-around.

The original code does in fact work, but depending on the "mode" you have matplotlib working in it may not update automatically. When I run the example code all at once (i.e. in a script) it works without any problems. When I run it line by line, after the call to the legend the canvas is still blank. To make it update the canvas with the new lines you can call `plt.draw()` right after `ax[:legend]()` and it will re-draw the current figure. 

If you want to be specific about which figure gets redrawn you can do `fig[:canvas][:draw]()`

**Comment by floswald** [comment]
awesome! it _does_ work! thanks!
