### ISSUE TITLE
Cannot use pcolor with julia 0.3.7 and matplotlib 1.4.3

### ISSUE THREAD

**Issue by ronisbr** [stevengj/PyPlot.jl#125]
Hi guys!

I am having a weird problem with PyPlot and the function pcolor.
The following code:

using PyPlot
pcolor(rand(10,10))

is giviging me this error:

ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'list' object has no attribute 'shape'",)
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 3018, in pcolor
    ret = ax.pcolor(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 4889, in pcolor
    X, Y, C = self._pcolorargs('pcolor', *args, allmatch=False)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 4682, in _pcolorargs
    numRows, numCols = C.shape

 in pyerr_check at /home/ronan.chagas/.julia/v0.3/PyCall/src/exception.jl:60
 in pycall at /home/ronan.chagas/.julia/v0.3/PyCall/src/PyCall.jl:92
 in pcolor at /home/ronan.chagas/.julia/v0.3/PyPlot/src/PyPlot.jl:370

I'm using python 2.7.8, matplotlib 1.4.3, and the lastest PyPlot.

I have already asked on Julia's mailing list and someone that are using python 2.7.6 and matplotlib 1.3.1 reported that this code is working properly. Since it is not possible to install here (openSUSE 13.2) this old matplotlib version, I need help to figure out what is the real problem.

Thanks,
Ronan

**Comment by stevengj** [comment]
Duplicate of stevengj/PyCall.jl#128?

**Comment by ronisbr** [comment]
Yes, it does seem similar to this bug. I tried many things but I was not be able to find a workaround for this problem. Maybe the array rand(10,10) is not being converted to a numpy array. Any ideas?

**Comment by stevengj** [comment]
What happens if you type `PyCall.npyinitialize()`?

**Comment by ronisbr** [comment]
Thanks very much @stevengj!

When I typed `PyCall.npyinitialize()`, I got:

ERROR: could not read __multiarray_api.h to parse PyArray_API SystemError("opening file /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h",2)
 in npyinitialize at /home/ronan.chagas/.julia/v0.3/PyCall/src/numpy.jl:69

Then I realized that I must install -devel packages in openSUSE (python-devel, python-numpy-devel). After that installation everything started to work properly.

Thanks one more time @stevengj and sorry about that, my bad :)

**Comment by stevengj** [comment]
Yeah, it kind of sucks that we require this.  Switching over to using the buffer protocol instead of NumPy will eliminate this dependency.
