### ISSUE TITLE
Unable to change fontsize in colorbar

### ISSUE THREAD

**Issue by kzapfe** [stevengj/PyPlot.jl#126]
Hello stevengj et all:

It seems that I cannot get the sintaxis form Julia,PyPlot to python,matplotlib right. I have been struggling for a while to change the fontsize of the colorbox in an "image" figure.  I've tried various approaches and methods, but some of them refuse to plot and others simply plot as before. This is one example 
```julia
otraimagen=imshow(CSDEjemplo, cmap="jet", origin="upper", vmin=-150, vmax=150)
cb=colorbar(otraimagen, ticks=[-150, +150],fraction=0.046, pad=0.04)
farofa=cb[:set_ticklabels]([{"Sink"}, {"Source"}])
``` 
Until here, everything works just fine. But then I try to use tick_params, or ticklabel_format in various ways (as "index" for cb or farofa) or as functions, and it seems that I cannot make them work. I also tried to use a fontdict as the example in pyplot_annotation.ipynb, but I seem to be only to call such method from xlabel or ylabel, not from colorbar[:set_ticklabels].

**Comment by stevengj** [comment]
I just googled "matplotlib colorbar tick size" and the [first link](http://stackoverflow.com/questions/15305737/python-matplotlib-decrease-size-of-colorbar-labels) told me what to do, e.g.:
```
imshow(rand(10,10)*300-150, cmap="jet", origin="upper", vmin=-150, vmax=150)
cb=colorbar(ticks=[-150, 0, +150],fraction=0.046, pad=0.04)
farofa=cb[:set_ticklabels](["Sink", "Zero", "Source"])
cb[:ax][:tick_params](labelsize=10) 
```
In general, you just do exactly the same thing as in Python, except that you change `foo.bar` in Python to `foo[:bar]` in Julia.

**Comment by kzapfe** [comment]
Thanks... it seems that I still cannot make the adecuate translation from . to [:]. I had some complaints with the "literals" before, so I put the {}, but you are right, they're not truly needed.
