### ISSUE TITLE
streamplot - always ends up in exception

### ISSUE THREAD

**Issue by Bradan** [stevengj/PyPlot.jl#129]
Hello,

Whenever I try to use streamplot, I'm getting this exception:

    ERROR: PyError (:PyObject_Call) <class 'AttributeError'>
    AttributeError("'list' object has no attribute 'shape'",)
      File "/usr/lib/python3.4/site-packages/matplotlib/pyplot.py", line 3339, in streamplot
        zorder=zorder)
      File "/usr/lib/python3.4/site-packages/matplotlib/axes/_axes.py", line 4204, in streamplot
        zorder=zorder)
      File "/usr/lib/python3.4/site-packages/matplotlib/streamplot.py", line 74, in streamplot
        grid = Grid(x, y)
      File "/usr/lib/python3.4/site-packages/matplotlib/streamplot.py", line 259, in __init__
        if len(x.shape) == 2:

It doesn't matter what I'm doing. See this for example:

    Pkg.add("PyPlot");
    using PyPlot;

    h = 0.1
    gridU, gridV = -0.5:h:4.0, -2.0:h:2.0;
    gridX = zeros(length(gridU), length(gridV));
    gridY = zeros(length(gridU), length(gridV));

    streamplot(gridU, gridV, gridX, gridY);

**Comment by dpsanders** [comment]
The following works for me, using vectors instead of ranges and interchanging `gridU` and `gridV`.
Note that there is no need to use semicolons at the end of each line in Julia.

```julia
h = 0.1
gridU, gridV = [-0.5:h:4.0], [-2.0:h:2.0]
gridX = zeros(length(gridV), length(gridU))
gridY = zeros(length(gridV), length(gridU))

streamplot(gridU, gridV, gridX, gridY)
```

**Comment by Bradan** [comment]
Hello,

Thanks, I'll remember your solution for the future. I use semicolons to be able to copy and paste it into the julia shell without printing every lines' result then.

Kind regards,
Daniel

**Comment by dpsanders** [comment]
Good idea with the semicolons for pasting.

Note that I was lazy and used `[1:2:5]` for converting the range to an array, which is deprecated in Julia v0.4. This should be `collect(1:2:5)` instead.

**Comment by dpsanders** [comment]
Instead of copying and pasting you can also just do `include("file.jl")`
