### ISSUE TITLE
Error initializing module PyPlot

### ISSUE THREAD

**Issue by juliohm** [stevengj/PyPlot.jl#133]
```julia
using PyPlot
```
>Warning: New definition 
    call(Type{PyCall.PyDict}, Base.Associative{#K<:Any, Any}) at /home/julio/.julia/v0.4/PyCall/src/conversions.jl:464
is ambiguous with: 
    call(Type{PyCall.PyDict}, Base.Associative{Any, #V<:Any}) at /home/julio/.julia/v0.4/PyCall/src/conversions.jl:463.
To fix, define 
    call(Type{PyCall.PyDict}, Base.Associative{Any, Any})
before the new definition.
Warning: error initializing module PyPlot:
Base.MethodError(f=pyinitialize, args=(Base.Libdl.DLHandle(ptr=0x0000000001c81f50), "/usr/bin/python"))

```julia
versioninfo()
```
>Julia Version 0.4.0-dev+4995
Commit 96cc970 (2015-05-25 20:43 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```
python --version
```
>Python 3.4.3

**Comment by stevengj** [comment]
You probably need to `Pkg.checkout("PyCall")`.  In general, if you are using a Julia 0.4 prerelease (which is mainly for developers at this point), you need to be on the git `master` versions of many packages.  End users should stick with Julia 0.3 until Julia 0.4 is released.

**Comment by juliohm** [comment]
Thank you @stevengj.
