### ISSUE TITLE
No working GUI backend found for matplotlib when using from REPL

### ISSUE THREAD

**Issue by yuyichao** [stevengj/PyPlot.jl#136]
I've got the following error when importing `PyPlot` from REPL. `IJulia` works fine and I remember it used to work from REPL as well.

This is on the master of `PyPlot` and `julia` with matplotlib `1.4.3` and python `3.4.3`.

```julia
julia> using PyPlot
WARNING: No working GUI backend found for matplotlib.
/usr/lib/python3.4/site-packages/matplotlib/__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```

**Comment by swt30** [comment]
I hit this earlier today - a bisect shows that JuliaLang/julia@4220ecebf107997ec7d44bd2a6236f7898e83473 caused it.

**Comment by stevengj** [comment]
Should be fixed with latest PyCall.

**Comment by ssfrr** [comment]
I also ran into this error message just now and it was resolved by upgrading my python libraries:

`pip install --upgrade numpy scipy matplotlib`
