### ISSUE TITLE
No output in IJulia

### ISSUE THREAD

**Issue by minad** [stevengj/PyPlot.jl#139]
plot just returns a PyObject but does't show anything. I am using julia 0.3.10, python3

**Comment by stevengj** [comment]
Are you using PyPlot (vs. `@pyimport matplotlib` with PyCall).  Can you try Python 2?

**Comment by minad** [comment]
I am using PyPlot. I don't have time to check it right now with python2 but maybe in a few days.

**Comment by minad** [comment]
Ok, it works with Python2. When will Python2 support be finally dropped? It would be a good signal if you start to remove the Python2 support from PyCall :)

**Comment by axsk** [comment]
For me the output works fine using (explicitly) `ion()` in the notebook.
But after calling `ioff()`, neither the `show()` nor the `draw()` functions display the plot.

This happens with Python 2.7.3, matplotlib 1.4.3, IJulia master, and PyPlot master as well as the PyCall imported version.

OT: I also discovered that using plot in one IJulia cell doesn't carry over the figure to the next cell, i.e. it is not possible to draw a figure over multiple cells. This probably is intended, but is there some way to control this?

**Comment by stevengj** [comment]
At the moment, I have no plan to drop Python2 support, as Python2 more widely used in science than Python3.

However, with the latest version of PyCall (`Pkg.checkout("PyCall"); Pkg.build("PyCall")`) plotting in IJulia works fine for me with Python 3.3 (from Anaconda) on OSX.
