### ISSUE TITLE
savefig passes a duplicate keyword argument

### ISSUE THREAD

**Issue by samuela** [stevengj/PyPlot.jl#141]
I got this error today:

```julia
julia> savefig(fig, "lds_pf.pdf")
ERROR: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError("print_figure() got multiple values for keyword argument 'dpi'",)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)

 in pyerr_check at /Users/samuelainsworth/.julia/v0.3/PyCall/src/exception.jl:58
 in pycall at /Users/samuelainsworth/.julia/v0.3/PyCall/src/PyCall.jl:91
 in savefig at /Users/samuelainsworth/.julia/v0.3/PyPlot/src/PyPlot.jl:371
```

It looks like PyPlot is passing a duplicate entry for the keyword argument `dpi`. It's not an internal matplotlib issue because I can click the save button in the plot window and it works fine.

**Comment by stevengj** [comment]
PyPlot is not passing a `dpi` keyword arg at all; this is something internal to Matplotlib.

It looks like you are just not calling `savefig` correctly.  See the [documentation for savefig](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.savefig): it just takes the filename as an argument, so you should not be passing `fig`.  i.e. just do `savefig("foo.pdf")` and it will save the current figure.

**Comment by samuela** [comment]
@stevengj Yes, that makes sense. Totally my fault. Sorry for the confusion!
