### ISSUE TITLE
plt.show() is bypassed in non-interactive mode

### ISSUE THREAD

**Issue by juliohm** [stevengj/PyPlot.jl#144]
If I write a script:

```julia
using PyPlot
imshow(ones(2,2))
plt.show()
```
and call it like `julia foo.jl`, the plot window closes automatically. This new behavior was introduced by the last update I did yesterday. Before the update I could see the plot and the process would hang until I close the window.

**Comment by stevengj** [comment]
That's odd, that script works for me (the plot window stays open until closed).  What does `versioninfo()` print on your system?

**Comment by stevengj** [comment]
Also, what is the output of `plt.get_backend()`?

**Comment by stevengj** [comment]
(Note that you can just type `show()`.  `plt.` is not needed.)

**Comment by stevengj** [comment]
I just pushed a patch that may be relevant (try `Pkg.checkout("PyCall"); Pkg.update()`)

**Comment by juliohm** [comment]
```julia
versioninfo()
```
>Julia Version 0.4.0-dev+5599
Commit c258b4c* (2015-06-25 20:49 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```julia
plt.get_backend()
```
>"TkAgg"

After the checkout of the master branch, it works as before.
