### ISSUE TITLE
view_init doesn't seem to work

### ISSUE THREAD

**Issue by ssfrr** [stevengj/PyPlot.jl#145]
```
scatter3D(rand(20), rand(20), rand(20)
gca()[:view_init](0.0, 0.0)
```

Is there another way to programatically set the view angle?

**Comment by stevengj** [comment]
The `view_init` function works, but it only takes effect the next time the plot is rendered.  e.g. if you run `savefig` you will notice that it uses the viewing angle you specify.  If you run it in IJulia (where the plot is rendered only after the entire cell executes), you will notice that it also determines the viewing angle of the final plot.

I don't know why it doesn't immediately update the "live" GUI display, but I think this is a problem with the Matplotlib backend, not with the Julia interface.  (Did you try it in Python?)

**Comment by ssfrr** [comment]
Just tried it in python and I'm seeing the same behavior, so looks like it's a matplotlib issue. I also noticed that when you click and drag the display jumps to whatever you set the view to. Thanks for the info.
