### ISSUE TITLE
Cannot index GridSpec array

### ISSUE THREAD

**Issue by berceanu** [stevengj/PyPlot.jl#149]
I am trying to adapt this `matplotlib` demo to Julia: http://matplotlib.org/users/plotting/examples/demo_gridspec03.py. I have this so far

```
using PyPlot
using PyCall
@pyimport matplotlib.gridspec as gspec

fig = plt.figure()

gs1 = gspec.GridSpec(1, 1)
gs1[:update](top=1.0, bottom=0.84)
ax1 = plt.subplot(gs1[0, 0])

gs2 = gspec.GridSpec(2, 1)
gs2[:update](top=0.77, bottom=0.44, hspace=0.0)
ax2 = plt.subplot(gs2[0, 0])
ax3 = plt.subplot(gs2[1, 0])

gs3 = gspec.GridSpec(2, 1)
gs3[:update](top=0.38, bottom=0.0, hspace=0.4)
ax4 = plt.subplot(gs3[0, 0])
ax5 = plt.subplot(gs3[1, 0])

fig[:savefig]("../../figures/gridspec.pdf")
plt.close(fig)
```

and I get
`ERROR: getindex has no method matching getindex(::PyObject, ::Int64, ::Int64)`.
Apparently I cannot access a particular element of the grid like `gs1[0,0]`.

**Comment by stevengj** [comment]
See the PyCall docs: *The biggest diffence from Python is that object attributes/members are accessed with o[:attribute] rather than o.attribute, and you use get(o, key) rather than o[key]. (This is because Julia does not permit overloading the . operator yet.) *

Instead of `gs[i,j]`, do `get(gs, (i,j))`.
```jl
fig = plt.figure()

gs1 = gspec.GridSpec(1, 1)
gs1[:update](top=1.0, bottom=0.84)
ax1 = plt.subplot(get(gs1, (0, 0)))

gs2 = gspec.GridSpec(2, 1)
gs2[:update](top=0.77, bottom=0.44, hspace=0.0)
ax2 = plt.subplot(get(gs2, (0, 0)))
ax3 = plt.subplot(get(gs2, (1, 0)))

gs3 = gspec.GridSpec(2, 1)
gs3[:update](top=0.38, bottom=0.0, hspace=0.4)
ax4 = plt.subplot(get(gs3, (0, 0)))
ax5 = plt.subplot(get(gs3, (1, 0)))
```

**Comment by stevengj** [comment]
Maybe I should implement `object[Integer...]`, however, for the common case of an integer-indexed (or tuple-of-integer-indexed) sequence like this.

**Comment by berceanu** [comment]
Thanks. Indeed, that sounds like a good idea, if it's not too much work :)

**Comment by berceanu** [comment]
On a further note, how does one index ranges, like `ax = plt.subplot(get(gs, (0, 0:2)))`. This currently produces an error.

**Comment by stevengj** [comment]
good question … I have no idea how Python represents this.

**Comment by stevengj** [comment]
Aha, they are implemented by `slice` objects in Python: https://docs.python.org/2/library/functions.html#slice

**Comment by stevengj** [comment]
So, you can do `pycall(pybuiltin("slice"), PyObject, 0,2)` to pass `0:2`.

(Cumbersome, I know, but you could write a `slice` wrapper function for this.)

**Comment by Pranay-modukuru** [comment]
> So, you can do `pycall(pybuiltin("slice"), PyObject, 0,2)` to pass `0:2`.
> 
> (Cumbersome, I know, but you could write a `slice` wrapper function for this.)

Could you please give an example for wrapper function.

**Comment by ajwheeler** [comment]
`slice(i,j) = pycall(pybuiltin("slice"), PyObject, i,j)`
