### ISSUE TITLE
Slow plot within Interact @manipulate macro

### ISSUE THREAD

**Issue by juliohm** [stevengj/PyPlot.jl#152]
Consider the following test case:

```julia
using Interact, Reactive
using DataStructures
using PyPlot

N = 3
A = dropdown(OrderedDict("Trend 1"=>ones(N,N), "Trend 2"=>eye(N)))

fig = figure()
@manipulate for A=A; withfig(fig) do
        subplot(1,2,1)
        imshow(eye(100))
        subplot(1,2,2)
        imshow(A)
    end
end
```

It works fine for `N=3`, but hangs for large values, let's say `N=200`.

```julia
versioninfo()
```
>Julia Version 0.4.0-dev+5599
Commit c258b4c* (2015-06-25 20:49 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```julia
Pkg.status()
```
> Interact                      0.1.6+             master
PyPlot                        1.5.3+             master

I'm on Python 3.4.3/Jupyter.

**Comment by juliohm** [comment]
Is this an issue of PyPlot or Interact?

**Comment by stevengj** [comment]
Have you tried it with some other output, not a plot?

**Comment by juliohm** [comment]
@stevengj, maybe, the fact is that it works with a small image, but it doesn't with a large one. What do you have in mind?

**Comment by juliohm** [comment]
@stevengj, can you reproduce the issue?

**Comment by juliohm** [comment]
I'm still experiencing this issue, how can I help fixing it?

**Comment by stevengj** [comment]
I think the problem is in the dropdown menu, not in PyPlot.  I get a hang just for:
```jl
using Interact, DataStructures

N = 300
A = dropdown(OrderedDict("Trend 1"=>ones(N,N), "Trend 2"=>eye(N)))

@manipulate for A=A
    A
end
```
That's why I suggested removing the plot.

Please file an issue with `Interact`.
