### ISSUE TITLE
tight_layout() gives error

### ISSUE THREAD

**Issue by colincsl** [stevengj/PyPlot.jl#153]
I would like to be able to call tight_layout() to automatically rescale my plots so that they fit better the figure. Currently I call `axis("tight")` after every `imshow(...)` which is annoying.

However, when I call `tight_layout()` I get the following error message:

<pre><code>PyError (:PyObject_Call) <type 'exceptions.ValueError'>
ValueError('max() arg is an empty sequence',)
  File "/Library/Python/2.7/site-packages/matplotlib/pyplot.py", line 1288, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/Library/Python/2.7/site-packages/matplotlib/figure.py", line 1663, in tight_layout
    rect=rect)
  File "/Library/Python/2.7/site-packages/matplotlib/tight_layout.py", line 325, in get_tight_layout_figure
    max_nrows = max(nrows_list)

while loading In[12], in expression starting on line 1

 in getindex at /Users/colin/.julia/v0.3/PyCall/src/PyCall.jl:255
 in pysequence_query at /Users/colin/.julia/v0.3/PyCall/src/conversions.jl:778
 in pytype_query at /Users/colin/.julia/v0.3/PyCall/src/conversions.jl:794
 in convert at /Users/colin/.julia/v0.3/PyCall/src/conversions.jl:844
 in pycall at /Users/colin/.julia/v0.3/PyCall/src/PyCall.jl:416
 in fn at /Users/colin/.julia/v0.3/PyCall/src/conversions.jl:188
 in close_queued_figs at /Users/colin/.julia/v0.3/PyPlot/src/PyPlot.jl:296
</code></pre>

**Comment by stevengj** [comment]
This is no different than in Python, I think: you can only call `tight_layout()` after a plot has been created.
