### ISSUE TITLE
Special charachters in title vs. legend

### ISSUE THREAD

**Issue by nilshg** [stevengj/PyPlot.jl#156]
Using ASCII characters in the legend works, while using them in titles creates blank boxes:

````
fig, ax = PyPlot.subplots()
ax[:plot](rand(100), label = "α")
ax[:legend](loc=0)
title("Random α")  # alternatively: ax[:set_title]()
plt[:show]()
````
This gives a plot with α displayed correctly in the legend, but an empty box in the title. Is this a bug or expected?

**Comment by nilshg** [comment]
Not sure why, but this problem has solved itself.

**Comment by stevengj** [comment]
I've never had a problem with Unicode display in Matplotlib... let me know if the problem re-appears.

**Comment by nilshg** [comment]
Just to prove that I'm not crazy: 

![missingascii](https://cloud.githubusercontent.com/assets/7264491/9608836/4a73f330-50c8-11e5-9d27-460156aa0975.JPG)

Don't know why this came back, I was able to properly output Unicode until just now.
With `@pyimport seaborn as sns` I get at least the legends correctly:

![seaborn](https://cloud.githubusercontent.com/assets/7264491/9609268/bf2878ac-50ca-11e5-8d65-763203cbffc6.JPG)

**Comment by stevengj** [comment]
Sounds like a font issue on your machine: looks like you are using a font that doesn't have those unicode characters.

**Comment by specter119** [comment]
with @nilshg 's script, i can't show "α" in both title and legend, @stevengj do you have any suggestions for this?  i can show a few unicode properly with PyPlot, "²" is the only one i found.

**Comment by stevengj** [comment]
@specter119, use LaTeX, e.g.   `title(L"\sqrt{\alpha^2}")`
