### ISSUE TITLE
Problems with Python path resolution in PyPlot and Julia 0.4.0-pre+7113 

### ISSUE THREAD

**Issue by dbrowne** [stevengj/PyPlot.jl#158]
| | |_| | | | (_| |  |  Version 0.4.0-pre+7113 (2015-08-31 17:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 092bcf4* (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using PyPlot
WARNING: could not import Base.help into PyCall
ImportError: No module named site
ERROR: LoadError: InitError: Failed to pyimport("matplotlib"): PyPlot will not work until you have a functioning matplotlib module.  ErrorException("could not load library \"python\"\ndlopen(python.dylib, 9): image not found")
 in __init__ at /Users/djb/.julia/v0.4/PyPlot/src/PyPlot.jl:232
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in require at ./loading.jl:210
during initialization of module PyPlot
while loading /Users/djb/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 653

 - PyPlot                        2.0.1

 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.5 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using PyPlot
INFO: Loading help data...
- PyPlot                        1.5.3

**Comment by stevengj** [comment]
Closing as a PyCall issue, not a PyPlot issue.

PyCall currently has some problems with 0.4, and I'm hoping to clean it up in the next few days.
