### ISSUE TITLE
using PyPlot just stopped working

### ISSUE THREAD

**Issue by jmxpearson** [stevengj/PyPlot.jl#159]
Have been using PyPlot with 0.4-dev without trouble until this morning when I pulled Julia master and ran make. Previous version of master was ~1week ago. Now the following happens on OSX (10.10.4), but not on Ubuntu (14.10). Am using current Julia master and ran Pkg.update on both. Using Anaconda for Python.

julia> using PyCall    (no error)

julia> using PyPlot
WARNING: could not import Base.help into PyCall
Could not find platform independent libraries \<prefix>
Could not find platform dependent libraries \<exec_prefix>
Consider setting $PYTHONHOME to \<prefix>[:\<exec_prefix>]
ImportError: No module named site

I see this is similar to some other issues that have been reported, but again, PyPlot has been working successfully on both systems until this most recent build. No previous path issues.

**Comment by neosado** [comment]
I had the same error when I was using PyPlot on my Mac. Julia version is 0.3.11. I was noticed that that happened once Compat was updated from 0.6.0 to 0.7.0. I pinned Compat to 0.6.0 then worked fine again. Hope it helps when you diagnose the issue.

**Comment by jmxpearson** [comment]
I think I found the error: stevengj/PyCall.jl#188
