### ISSUE TITLE
API for embedding plots

### ISSUE THREAD

**Issue by jverzani** [stevengj/PyPlot.jl#16]
Is there a way to embed plots within a PySide GUI? I can follow along with http://wiki.scipy.org/Cookbook/Matplotlib/PySide to create the fig object and can draw on that, but don't know how to set that fig object to be the active figure that PyPlot.jl's exported plot commands use. Is there something like manager["canvas"]["setFigure"]()? I don't see that symbol in the manager["canvas"] object.

Maybe I'm going about this wrong. Any help would be appreciated.

**Comment by stevengj** [comment]
Your links seem broken; the [example here](http://matplotlib.org/examples/user_interfaces/embedding_in_qt4.html) doesn't uses a `setFigure` method.

**Comment by jverzani** [comment]
Wow, thanks for following up on this.

**Comment by stevengj** [comment]
Yeah, I just came across this randomly...
