### ISSUE TITLE
and another "using PyPlot" error...

### ISSUE THREAD

**Issue by martinzh** [stevengj/PyPlot.jl#160]
I'm on a OSX 10.10.5 MacBook Pro

This is the Julia versioninfo output: https://gist.github.com/martinzh/9ea1a05685ac1a8cf209

The error I get when I try: 

julia> using PyCall

julia> pyinitialize()
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Deimos:~ martinzh$ julia

or:

ulia> using PyPlot
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

which python gives: /Users/martinzh/anaconda/bin/python

within Python I get the correct prefix and exec_prefix:

Deimos:~ martinzh$ ipython
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys

In [2]: sys.prefix
Out[2]: '/Users/martinzh/anaconda'

In [3]: sys.exec_prefix
Out[3]: '/Users/martinzh/anaconda'

and matplotlib loads without errors.

And finally the output of Pkg.test("PyCall"):

julia> Pkg.test("PyCall")
INFO: Testing PyCall
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
================================================================================[ ERROR: PyCall ]=================================================================================

failed process: Process(`/Applications/Julia-0.3.11.app/Contents/Resources/julia/bin/julia /Users/martinzh/.julia/v0.3/PyCall/test/runtests.jl`, ProcessExited(1)) [1]

==================================================================================================================================================================================
INFO: No packages to install, update or remove
ERROR: PyCall had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67

Any ideas??

**Comment by martinzh** [comment]
# UPDATE

Setting:

```
export PYTHONHOME=/Users/martinzh/anaconda/  
```

in .bash_profile solved the problem

**Comment by stevengj** [comment]
Hopefully should be fixed in PyCall `master` (`Pkg.checkout("PyCall"); Pkg.build("PyCall")`), which shouldn't require you to set `PYTHONHOME`

**Comment by martinzh** [comment]
Thanks for answering, I've tried and it's fixed in PyCall ```master```
