### ISSUE TITLE
using PyPlot fails with missing encodings module

### ISSUE THREAD

**Issue by mzaffalon** [stevengj/PyPlot.jl#161]
On Julia 0.3.11 on Windows 7 64 bits, since a couple of days I see the following

```
C:\Users\michele.zaffalon>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> run(`python --version`)
Python 3.4.1 :: Anaconda 2.1.0 (64-bit)

julia> using PyPlot
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```

PyPlot has been working until a few days ago when I updated conda and the packages (I do not remember what packages were updated though). Wiping out the .julia directory (which is located on a local drive) does not help.

**Comment by mzaffalon** [comment]
Whereas `using PyPlot` fails from any local directory I try to call it, `using Gadfly` fails only when Julia is started from some (still local) specific directories. The error message for Gadfly (when it fails) is the same

```
julia> using Gadfly
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```

**Comment by stevengj** [comment]
I'm confused, Gadfly doesn't even use Python ...

**Comment by mzaffalon** [comment]
That's what I thought as well...

**Comment by tbreloff** [comment]
If you quit/reload julia and do `using Gadfly` immediately, does it still give that python error?  If so I suspect this issue goes beyond PyPlot...

**Comment by mzaffalon** [comment]
Yes, even when `using Gadfly` is the first command of a new Julia session.

I still cannot figure out when it happens: starting Julia and trying to import PyPlot always fails, with Gadfly seems to depend on the directory in which I start Julia.

I tried on a different Windows 7 64 bit computer with Anaconda Python 3 installed, and observed none of these problems.

**Comment by tbreloff** [comment]
Do you have a `.juliarc.jl` file that might be doing something on startup?  Also, try deleting everything from your `~/.julia/lib/v0.4/` directory before starting up again.

**Comment by mzaffalon** [comment]
No `.juliarc.jl`. Should I delete the v0.4 directory even if I am using 0.3.11?

**Comment by tbreloff** [comment]
Oh... nevermind that shouldn't impact you.  I was concerned about 0.4 precompilation.  It could be your python version, although it's super strange that `using Gadfly` would do anything related to python.  Sorry I'm not of more help.

Depending on how desperate you get, you could consider build 0.4 from source (using the `release-0.4` branch)

**Comment by mzaffalon** [comment]
No problem, thank you for your help.

I am so desperate (presentation is today) that I am generating the Python plotting code in Julia!

**Comment by stevengj** [comment]
You could also try Anaconda with Python 2.x, which is the most tested with PyPlot.

**Comment by stevengj** [comment]
Though it works for me with Anaconda Python 3.3 on Mac.

**Comment by stevengj** [comment]
Do you have something in your `.juliarc` file that might be triggering this?

**Comment by mzaffalon** [comment]
Looks like it is gone. I see that you have updated PyCall and PyPlot.

**Comment by stevengj** [comment]
Great!

**Comment by mzaffalon** [comment]
Is there any reason your update solves the `using Gadfly` at the same time?

**Comment by stevengj** [comment]
No, because Gadfly has nothing to do with PyCall as far as I understand it.
