### ISSUE TITLE
Cannot using pyplot on Mac with Julia 0.4rc1

### ISSUE THREAD

**Issue by krzakala** [stevengj/PyPlot.jl#162]
I use Julia 0.4 (rc1) and the python installed by anaconda

I tried 
using Pyplot
WARNING: could not import Base.help into PyCall
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

However, it seems to me julia use the correct verison of python
julia> run(`python --version`)
Python 2.7.10 :: Anaconda 2.2.0 (x86_64)

Besides, matplotlib works fine onpython

**Comment by tbreloff** [comment]
Try `using PyPlot`  (capitalization)

**Comment by krzakala** [comment]
Sure :-)

using PyPlot
WARNING: could not import Base.help into PyCall
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

**Comment by krzakala** [comment]
Solved, using 
Pkg.checkout("PyCall")
Pkg.build("PyCall")
