### ISSUE TITLE
PyPlot, @doc not defined error?

### ISSUE THREAD

**Issue by GeraintPratten** [stevengj/PyPlot.jl#169]
Hi, I'm getting the following error when trying to load PyPlot. It was working a few days ago?

ERROR: @doc not defined
 in include at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/geraintpratten/.julia/v0.3/ColorTypes/src/ColorTypes.jl, in expression starting on line 86
while loading /Users/geraintpratten/.julia/v0.3/Colors/src/Colors.jl, in expression starting on line 5
while loading /Users/geraintpratten/.julia/v0.3/PyPlot/src/colormaps.jl, in expression starting on line 4
while loading /Users/geraintpratten/.julia/v0.3/PyPlot/src/PyPlot.jl, in expression starting on line 481

**Comment by GeraintPratten** [comment]
I'm also getting errors such as:

ERROR: ArgumentError("haskey of NULL PyObject")
 in plot at /Users/geraintpratten/.julia/v0.3/PyPlot/src/PyPlot.jl:444

Even when plotting the examples given in the documentation etc. Thanks!

**Comment by mbeltagy** [comment]
I am also getting similar errors. It happened right after I did a *Pkg.update()* this morning. 
```
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/elbeltagy/.julia/ColorTypes/src/ColorTypes.jl, in expression starting on line 86
while loading /home/elbeltagy/.julia/Colors/src/Colors.jl, in expression starting on line 5
while loading /home/elbeltagy/.julia/PyPlot/src/colormaps.jl, in expression starting on line 4
while loading /home/elbeltagy/.julia/PyPlot/src/PyPlot.jl, in expression starting on line 481
```

**Comment by mbeltagy** [comment]
The same error persisted after I checked out the master  Pkg.checkout("PyPlot")
If I switch from the stable Julia 0.311 to 0.4.0-rc2 the errors disappear.

**Comment by mbeltagy** [comment]
A single line change in ColorTypes.jl fixed it. See this pull request:
https://github.com/JuliaGraphics/ColorTypes.jl/pull/14

**Comment by mbeltagy** [comment]
@GeraintPratten , if you do Pkg.update() now, you should see no errors. Please check and close this issue if everything works well.

**Comment by stevengj** [comment]
Closing as not a PyPlot issue in any case.
