### ISSUE TITLE
Using PyPlot fail with rc3

### ISSUE THREAD

**Issue by krzakala** [stevengj/PyPlot.jl#173]
using Pyplot fail with rc3.

I fix it, using checkout and build for both pyplot and pycall for a number of time, but when I exit Julia, closemy computer, and start it again, I would get the same problem. e.g.:

using Pyplot
INFO: Recompiling stale cache file /Users/florent/.julia/lib/v0.4/Pyplot.ji for module Pyplot.
WARNING: replacing module PyPlot
WARNING: Method definition pygui(Bool) in module PyPlot at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:285 overwritten in module PyPlot at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:285.
WARNING: Method definition connect(Union{Symbol, AbstractString}, Function) in module PyPlot at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:469 overwritten in module PyPlot at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:469.
WARNING: Method definition step(Any, Any) in module PyPlot at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:464 overwritten in module PyPlot at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:464.
WARNING: Method definition step(Array, Any, Any) in module PyPlot overwritten in module PyPlot.
WARNING: Method definition close() in module PyPlot at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:467 overwritten in module PyPlot at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:467.
WARNING: New definition 
    close(Union{Integer, PyPlot.Figure, Symbol, AbstractString}) at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:466
is ambiguous with: 
    close(Union{Integer, Symbol, AbstractString, PyPlot.Figure}) at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:466.
To fix, define 
    close(Union{Integer, Symbol, AbstractString})
before the new definition.
WARNING: Method definition fill(AbstractArray, AbstractArray, Any...) in module PyPlot at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:471 overwritten in module PyPlot at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:471.
WARNING: Method definition fill(Array, AbstractArray, AbstractArray, Any...) in module PyPlot overwritten in module PyPlot.
WARNING: Method definition show() in module PyPlot at /Users/florent/.julia/v0.4/PyPlot/src/PyPlot.jl:450 overwritten in module PyPlot at /Users/florent/.julia/v0.4/Pyplot/src/Pyplot.jl:450.
WARNING: requiring "Pyplot" in module "Main" did not define a corresponding module.

**Comment by stevengj** [comment]
Do `using PyPlot`.    Note the case.  You're running into JuliaLang/julia#5789, which was recently fixed.
