### ISSUE TITLE
What needs to be done to remove `Windows version 10.0 detected`

### ISSUE THREAD

**Issue by mmoh** [stevengj/PyPlot.jl#175]
Haven't had any issues on Windows 10

```julia
julia> using PyPlot
Qt: Untested Windows version 10.0 detected!
```

**Comment by stevengj** [comment]
This error message is [coming from Qt](http://stackoverflow.com/questions/32966226/how-solve-qt-untested-windows-version-10-0-detected), not from PyPlot.
