### ISSUE TITLE
error indexing axes object

### ISSUE THREAD

**Issue by berceanu** [stevengj/PyPlot.jl#178]
Minimal example:

```julia
using PyPlot
fig, axes = plt.subplots(2,2)
axes[1,1]
```

`ERROR: getindex has no method matching getindex(::PyObject, ::Int64, ::Int64)`

Using PyPlot 1.5.3 and Julia 0.3.11-pre+20 on Arch Linux with matplotlib 1.4.3-4 (python 3.5.0-2).
I have a lot of similar usage examples in my code, I think they all broke the last time I updated matplotlib, iirc.

**Comment by stevengj** [comment]
Nowadays this needs to be `plt[:subplots](2,2)`.  (This was changed in order to make precompilation more efficient in Julia 0.4).

**Comment by berceanu** [comment]
I am avoiding an upgrade to `Julia` 0.4 as I do not have the time to deal with all the breaking changes atm. Trying `fig, axes = plt[:subplots](2,2)` on my current setup gives `ERROR: getindex has no method matching getindex(::Module, ::Symbol)`.

So, if I understand you correctly, it is not the version of `matplotlib` that is causing the problem. Since my version of `Julia` did not change, I can only assume that this change was introduced at *some point* in `PyPlot`. 

Perhaps a quick fix would be checking out an older version of `PyPlot` (which one?) and doing a `Pkg.pin()` on it?

**Comment by stevengj** [comment]
Should be fixed by the latest PyCall https://github.com/stevengj/PyCall.jl/commit/2a32317f8da4165b3e0d606b48552cc32af2cb58
