### ISSUE TITLE
PyPlot can't close first figure created using Python 2.7.10 matplotlib

### ISSUE THREAD

**Issue by lewisl** [stevengj/PyPlot.jl#179]
set hard env variable to version of python to use.
Pkg.Add("PyCall")
Pkg.Add("PyPlot")
using PyPlot
plot(1:5)    # this can never be closed with close()
scatter(rand(25),rand(25))   # this does close()   !!!

This happens over and over.  Something broke!

**Comment by lewisl** [comment]
Went back to 2.7.9.  Same problem.

**Comment by lewisl** [comment]
Wow.  Frustrating.  Same problem with 3.5. 

I had previously deleted my .julia folder, deleted my Julia installation and started completely over.

For weeks this worked and now it doesn't.  What I've done differently is to install the latest versions of Python.  Then I downgraded Python 2.7.10 to 2.7.9 as above by deleting Python 2.7.10 entirely.

These are clean installs from Python.org.  I don't want to use conda because I use Python for real, so the embedded thing is just a duplicate. I had not previously used conda when it used to work.

I have no explanation for this.  The fragility of package management is frustrating.  This is just a really BAD use of people's time.

**Comment by lewisl** [comment]
The first window is "spurious".  It is not addressable.  If you draw 2 more plots in new figures and run plt[:get_fignums]() you will get figure numbers for the latter 2, but not the first.  If you close() the latter 2, the window of the first remains visible.  If you run plt[:get_fignums] again you get an empty vector--there is no figure.  So, both Julia and python/matplotlib have abandoned the window.  If you try to close it, you get spinning beachball.  Julia is not blocked:  the repl is fine.   The only way to close the spurious plot window is to kill Julia.

**Comment by lewisl** [comment]
Sorry for being a bit pissy.  Looking at the Python versions I was chasing the wrong theory.  I stripped Python again and let Pkg. install using conda.  This brings in Python 2.7.10 and matplotlib 1.4.3.  The problem above appears to be caused by using matplotlib 1.5.0. I will confirm this with standalone Python.  By the way, there is nothing wrong with PyCall managing the dependency stack "internally" with conda.  Keeps Julia's copy separate.  You can use it, of course, if you path to it properly.

Well, it is not just matplotlib 1.5.0.  There is also something about the latest python 2.7.10 installer that even with matplotlib 1.4.3 the first figure window drawn cannot be closed.  Now, I'll go back a version and try to confirm this.

Well, I went back to Python 2.7.9.  It still doesn't work even with matplotlib 1.4.3.  This means I have a mangled usr/bin and usr/local/bin. A pox on Unix and all of its derivatives.  There is no reliable and safe way to purge usr/bin without destroying something.

So, now I must use conda and perhaps never have system pythons installed properly.  

I am not sure that reinstalling os x will fix this.  A pox on 'nix.

**Comment by lewisl** [comment]
I am out of theories.  I guess I will need 3G of Python's on my machine.  1 for Julia, 2 for Python 2.7, 3 for Python 3.5.

Pathetic.  It once worked.  Never upgrade or touch anything.

**Comment by lewisl** [comment]
I am back in business using conda, but I would like to understand if I can get back to using open Python.

**Comment by stevengj** [comment]
Managing your own Python distribution is a mess, no doubt about it; it is easy to break things.  That's why I gave up a long time ago and switched to conda.

One option is to download and install Anaconda systemwide, and use that from Julia.

**Comment by lewisl** [comment]
On the mac managing Python is really easy. This remains an issue. What can I do to help debug it?

**Comment by lewisl** [comment]
Anyone?  I don't have anywhere to look...

**Comment by lewisl** [comment]
Spent 5 hours on this over the past 2 days.  Uninstalled/reinstalled Julia and all packages.  Tried both the self-contained Python (conda) and system Python.  Conda python closes the first plot; system python does not.  Looked at pycall deps:  could see no major differences except the paths that were set and true/false for conda =.   

Outputs to the repl are essentially the same.  Both are using :tk for drawing. Using lower level direct call seem to work in both cases so PyCall/PyPlot are certainly making the connection to the installed Python.

Looked through source and the primary differences for conda are the tests for pre-reqs and the installation of missing pre-reqs.  I am not failing on those tests.

Any suggestions for how to debug the calls to python and returns from python through the PyPlot functions?  The preprocessor steps (@eval) that generate all of the Julia callables don't make it easy to insert print statements.  I tried @debug, but that is not really meant to work across "using" I think.

There is something about how the first figure object is generated that is getting lost so that a subsequent close() call back to matplotlib is not closing the "current" figure--when we are doing the first plot.  This is true even when a figure IS explicitly requested and assigned to a variable in Julia, e.g:

fig = figure()
plot(1:5)
close(fig)

In the repl, PyObjects that are returned seem OK (at least they appear to be similar to later PyObjects for subsequent figures).

I'm stumped.

**Comment by lewisl** [comment]
SOLVED.

Tipoff 1: After creating the first plot, there was a fignum returned for it.  After close(), the fignum list was empty, but the plot window was still there on the screen for all the world to see (well, maybe just me...).  This suggests that the handshaking between Julia and Python was just fine, but the handshaking between Python and tcl/tk was suspect.

Tipoff 2:  I had access to another Mac on which everything worked perfectly between PSF (Python Software Foundation) Python and Julia.  I noted that it was using ActiveState TCL 8.5.15.  On the offending Mac, I was using ActiveState TCL 8.5.18.  

PSF cautions Mac users not to use tcl 8.6 because current Pythons 2.7 series and Python 3.4 won't link to it.  So, I needed something in the 8.5 release series.  I believe that Python 3.5 may link with tcl 8.6 builds, but I am relying on some internet posts, not PSF directly.

ActiveState only allows certain versions to be downloaded as "community editions"--and their builds are NOT open source.  But, they do allow 8.5.18 and 8.5.17 to be downloaded.  And, they supply a very nice uninstall script that really cleans up after itself, including symlinks scattered about.  A nice purge of 8.5.18 followed by downloading and installing 8.5.17 and voila:  everything now works.

tcl 8.5.18 works properly with Python and matplotlib directly but not when Python and matplotlib are being called by Julia.  I did not figure out what that incompatibility might be.  It's unavoidable that these deep dependency stacks will exhibit fragility (that is a bit hard to diagnose).

Unfortunately, homebrew only provides tcl versions after 8.6, perhaps because tcl is not open source.  So, this might be worth continuing to investigate.  Old versions are available from tcl's sourceforge repository at http://sourceforge.net/projects/tcl/files/Tcl/<version string>/.  These can be built on os x with Xcode command line tools with ./configure, make, make install in the expanded directory.

I spent a fair amount of time trying things with PyCall and PyPlot that didn't turn up anything, but I learned my way--a bit--around them.

**Comment by stevengj** [comment]
Glad you figured it out, and thanks for following up!

However, the [main version of Tcl](http://www.tcl-lang.org/) is open source (but it is under a BSD license that allows proprietary forks like ActiveTcl).

I'm using a Mac with the built-in version of Tcl (tcl 8.5), and it works fine.

**Comment by lewisl** [comment]
I'll try that. The old warnings from PSF may be out of date after is x 10.11.





On Fri, Nov 20, 2015 at 4:52 PM -0800, "Steven G. Johnson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Glad you figured it out, and thanks for following up!

However, the main version of Tcl<http://www.tcl-lang.org/> is open source (but it is under a BSD license that allows proprietary forks like ActiveTcl).

I'm using a Mac with the built-in version of Tcl (tcl 8.5), and it works fine.

-
