### ISSUE TITLE
Using pyplot fails with latest anaconda

### ISSUE THREAD

**Issue by Mike43110** [stevengj/PyPlot.jl#180]
Updating anaconda or using the miniconda package by setting the environment to "" has using pyplot fail with no gui found. Will post the error lot later as I am currently  not at the pc with the updated anaconda.

**Comment by Mike43110** [comment]
```
julia> using PyPlot
C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
WARNING: No working GUI backend found for matplotlib.
ERROR: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('DLL load failed: The specified module could not be found.',)
  File "C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\pyplot.py", line 27, in <module>
    import matplotlib.colorbar
  File "C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\textpath.py", line 22, in <module>
    from matplotlib.mathtext import MathTextParser
  File "C:\Users\micha\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\mathtext.py", line 63, in <module>
    import matplotlib._png as _png

 [inlined code] from C:\Users\micha\.julia\v0.4\PyCall\src\exception.jl:81
 in pyimport at C:\Users\micha\.julia\v0.4\PyCall\src\PyCall.jl:79
 in __init__ at C:\Users\micha\.julia\v0.4\PyPlot\src\PyPlot.jl:250
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
during initialization of module PyPlot
```

**Comment by stevengj** [comment]
You closed this; is it working for you now?

**Comment by Mike43110** [comment]
No, I was actually going to post but the wonderful comment and close button positions...

Couldn't get it working on my other PC either with the same error.

**Comment by stevengj** [comment]
Are you using the default matplotlib backend (Tk) or have you set up your `matplotlibrc` to use a different backend?

**Comment by stevengj** [comment]
Could this be the same as #151?

**Comment by Mike43110** [comment]
Clean install on a new format on windows using Julia 0.4.

I am not sure. I tried
```
ENV["LD_LIBRARY_PATH"]="C:/Users/mica/.julia/v0.4/Conda/deps/usr/lib"
using PyPlot
```
and god the same error.

I haven't changed the matplotlib backend at all.

**Comment by Mike43110** [comment]
Hi, I just checked with an old version of anaconda(2.3) and it works with that fine.
It seems to be only an issue with Anaconda 2.4.

**Comment by stevengj** [comment]
What Matplotlib backend are you using?  e.g. if you are using the qt backend maybe you need `import Conda; Conda.add("pyside")`

**Comment by dhoegh** [comment]
This is a dup of https://github.com/stevengj/PyCall.jl/issues/209. It is actually an upstream issue with anaconda which should be fixed in near future. So using an older Anaconda for now seems like a good solution.

**Comment by lewisl** [comment]
Yet another reason to give up on Anaconda.  I am writing up the relative sizes and install times for PSF Python and pip'ing needed packages vs the Julia internal Python using miniconda.  I am still doing some research, but the PSF and pip option looks very good on OS X, but with some issues on Windows that can be solved less easily.

**Comment by stevengj** [comment]
This has reportedly been fixed upstream by Anaconda.
