### ISSUE TITLE
contourf and levels only working with explicit keyword

### ISSUE THREAD

**Issue by abieler** [stevengj/PyPlot.jl#182]
R = rand(-10:0.1:10,(10,10))
contourf(R, [0.0,6], colors=("k"))

does not work, one has to explicitly call:

contourf(R, levels=[0.0,6] ,colors=("k"))

no big deal, but worth mentioning I guess
as the first case works in python.

For completeness here the error message one
gets in the first case:
ERROR: ArgumentError: if 2nd arg is column vector, 1st arg must be row or column vector
in contourf at ...../.julia/v0.4/PyPlot/src/PyPlot.jl:595

**Comment by stevengj** [comment]
Thanks, should be fixed now.
