### ISSUE TITLE
openSUSE Leap 42.1: PyPlot triggers call to Yast

### ISSUE THREAD

**Issue by colbec** [stevengj/PyPlot.jl#183]
Question: I am using Julia Version 0.5.0-dev+1534 (2015-12-01 06:23 UTC) - when I start PyPlot and the system sees a need to recompile stale cache files, the process gets to BinDeps (approximately) and Yast pops up asking for root permissions. I can say yes or no, Yast appears to not know what to do since the list of installs is empty, and the process seems to complete fine and simple plots can be generated.

I'm trying to find the most appropriate place to register this issue, it might be here or over at BinDeps. What other information can I glean from Julia/PyPlot?

**Comment by stevengj** [comment]
Probably should be filed with BinDeps.  PyPlot itself does not use BinDeps directly, and as far as I can tell none of the PyPlot dependencies (some of which require BinDeps) use YaST packages.

**Comment by colbec** [comment]
I think I have some more information here which does not involve BinDeps.

```
versioninfo()
Julia Version 0.5.0-dev+3192
Commit fdbcdf7* (2016-03-17 14:33 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

When starting Julia 5 with `--compilecache=no`, I then include a script which starts with 
```
using DataFrames
using Distances
using PyPlot

println("Loading raw data...")
```
Before the println() can be processed I get a request to access root permissions through Yast as above. Watching the process messages both before and after the spurious request I get the output as listed in gist https://gist.github.com/colbec/6b0b39e57b32d8772b58

The relevant part appears to be 
```
WARNING: deprecated syntax "call(o::PyObject, ...)".
Use "(o::PyObject)(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(PyObject), ...)".
Use "(::Core.kwftype(PyObject))(...)" instead.

WARNING: deprecated syntax "call(::Type{PyAny}, ...)".
Use "(::Type{PyAny})(...)" instead.

######## cancel call to root privileges here ############

WARNING: deprecated syntax "call(f::Figure, ...)".
Use "(f::Figure)(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Figure), ...)".

```
While this does not mean much to me, perhaps it will add a straw to the haystack of information.
