### ISSUE TITLE
Multiple plot windows requires FILO

### ISSUE THREAD

**Issue by colbec** [stevengj/PyPlot.jl#189]
In a script, say we run three plot commands each in a separate `figure()`.
If the last call in the script is to `show()` the figures, the script blocks allowing examination of the figures, good. To end the script we close down the figure windows; if the order of shutdown is anything other than first in last out then the script crashes with a segfault.
Close 3, close 2, close 1 : script terminates quietly. Also close 2, close 3, close 1 is good.
Close 1 then 2,3 : segfault. Close 2, 1, 3 : segfault.
It may only be an inconvenience, but perhaps indicates other things not terminating properly.

**Comment by stevengj** [comment]
What happens if you try the same thing in Python (with the same backend)?

**Comment by colbec** [comment]
Same thing, segmentation fault.
Example Python code for test:
```
import matplotlib.pyplot as plt
a = [1,2,3,4,5]
plt.figure(1)
plt.plot(a)
plt.figure(2)
plt.plot(a)
plt.figure(3)
plt.plot(a)
plt.show()

```

**Comment by stevengj** [comment]
If it happens in Python, then it is a Matplotlib bug and you should report it there.
