### ISSUE TITLE
asking for too large a figure crashes Julia (v0.4.3)

### ISSUE THREAD

**Issue by maxlarsen** [stevengj/PyPlot.jl#191]
Hi everyone! See below.

~~~
julia> figure(figsize=(300,3))
PyPlot.Figure(PyObject <matplotlib.figure.Figure object at 0x7f445ce17610>)
julia> figure(figsize=(500,3))
[CRASH]
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Serial number of failed request:  5209
  Current serial number in output stream:  5210
~~~

Max

**Comment by stevengj** [comment]
Do you get the same error if you try this in Python?

**Comment by maxlarsen** [comment]
Hi, sorry about the delay. I do get the error in Python. This was on my laptop. I don't get the error on my desktop in Julia. Happy to close or to provide more info if useful.

**Comment by stevengj** [comment]
If you get the error in Python too, then it is a Matplotlib bug and should be filed there.
