### ISSUE TITLE
using PyPlot from os console

### ISSUE THREAD

**Issue by swiesend** [stevengj/PyPlot.jl#194]
Hello!

First of all thank you so much for developing this exciting stuff! I am very new to julia and I am trying to plot some basic stuff. Thus I followed the available examples and its was quite straight forward use PyPlot with all the explanations in the console for the next step. But I got stuck when trying to run a `.jl` script from my os console (not from within the julia prompt, there it works fine):

>     $ julia plot.jl 
>     INFO: Loading help data...

and nothing happens.

this is the `plot.jl`:

    using PyPlot
    
    x = collect(-pi:0.2:pi);
    plot(x, sin(x), ".")

 What am I doing wrong or is this intended behaviour?

**Comment by tbreloff** [comment]
It's intended.  When you're at the REPL (Julia prompt), it implicitly calls `display(ans)` where `ans` is the result of the command.  When running a script it doesn't have this behavior, so you need to explicitly call display on your plot.

**Comment by swiesend** [comment]
ok, bbut when I try to call the `display` function explicitly:

    using PyPlot
    x = collect(-pi:0.2:pi);
    display(plot(x, sin(x), "."))

I get the following:

    $ julia plot.jl 
    INFO: Loading help data...
    1-element Array{Any,1}:
     PyObject <matplotlib.lines.Line2D object at 0x7fbc2853bcd0>

Or is there no way doing it like I want?

**Comment by tbreloff** [comment]
You're right... instead of `display`, after the plot command you can do:

```
PyPlot.plt[:show]()
```

There may be a shortcut for this, but I don't remember.  I tend to deal with PyPlot from a lower level for my package [Plots](https://github.com/tbreloff/Plots.jl).

**Comment by swiesend** [comment]
Thanks a lot Thomas! That's working fine!

And I definitely going to have a look `Plots.jl`, too.

Offtopic:
Can I also use this in the Jupyter QtConsole? Do you know a good tutorial/example?

**Comment by tbreloff** [comment]
I can't comment on QtConsole as I've never used it, but I use Jupyter/IJulia a lot and it works really well.  PyPlot has some trickiness occasionally if you want to have both inline graphics and an interactive GUI... if you run into trouble let me know (though I'll be more help if you're accessing it through Plots)

**Comment by stevengj** [comment]
If you are running Julia interactively, e.g. in the REPL, then it runs Matplotlib in interactive mode, where plots appear immediately.   If you are running Julia non-interactively, from a script, then it runs Matplotlib in non-interactive mode, where you have to run `show()`.

It is enough to run `show()` ... you don't need `PyPlot.plt[:show]()`

**Comment by stevengj** [comment]
I've added some documentation to clarify this situation.
