### ISSUE TITLE
PyPlot color argument bug

### ISSUE THREAD

**Issue by tbreloff** [stevengj/PyPlot.jl#195]
I tried to figure this out myself, but couldn't.  @stevengj I'm hoping you'll have a quick answer.  Similar to https://github.com/tbreloff/Plots.jl/issues/145 I can't seem to plot a series with the same number of points as the color tuple I'm passing in.  Here's a simple example:

```
import PyPlot
PyPlot.scatter(1:3, rand(3), c = (0, 0.2, 1), s = 900)
```

Instead of plotting 3 points all with the same color, it plots 3 points with different colors seemingly pulled from a "blues to reds" colormap.  The important part from the matplotlib docs:

> Note that c should not be a single numeric RGB or RGBA sequence because that is indistinguishable from an array of values to be colormapped. c can be a 2-D array in which the rows are RGB or RGBA, however, including the case of a single row to specify the same color for all points.

I thought: "All I need to do is make it a matrix!"  However, all of these versions give exactly the same result:

```
... c = [0, 0.2, 1] ...
... c = Vector[[0, 0.2, 1]] ...
... c = [(0, 0.2, 1)] ...
... c = [0 0.2 1] ...
... c = Matrix[[0 0.2 1]] ...
```

Any ideas?  Thanks.

**Comment by stevengj** [comment]
I dunno, but `scatter(1:3, rand(3), c = ((0,0.2,1),(0,0.2,1)), s = 900)` works for me (i.e. repeating the color twice is enough).   Does anything work in Python?

**Comment by lstagner** [comment]
I was playing around with this and i discovered that using a RGBA value works
```
using PyPlot
scatter(1:3, rand(3), c=(0, 0.2, 1, 1), s=900)
```

**Comment by stevengj** [comment]
Did you try it in Python?

**Comment by lstagner** [comment]
Yes the bug exists in python as well.

**Comment by stevengj** [comment]
If the bug exists in Python, then it should be reported upstream to Matplotlib.
