### ISSUE TITLE
using PyPlot is slow (> 1s)

### ISSUE THREAD

**Issue by ufechner7** [stevengj/PyPlot.jl#196]
Hello,

with a very fast gaming notebook and an SSD I get the following loading time:
julia> tic(); using PyPlot; toc()
elapsed time: 2.466866058 seconds

Import matplotlib in Python needs about 10% of this time.
This should be improved. Currently Julia feels to be much slower then Python.

What are the reasons for these load times?

Uwe

**Comment by stevengj** [comment]
See #143.

**Comment by ufechner7** [comment]
I don't like it, if you close an issue by referencing another issue that is closed by referencing another issue that is closed without giving any good reason. 

Please reopen this issue until it is fixed, or reference another issue that is not closed.

**Comment by stevengj** [comment]
On my machine, `using PyCall` takes about 25% of the time for `using PyPlot`, `using Colors` takes about 10% of the time, `pyimport("matplotlib.pyplot")` takes about 28% of the time (and this is time spent in Python).  Together, this is 63% of the time for `using PyPlot` spent on things that are out of the control of this package.  So, my conclusion is that there are no really dramatic gains to be had by changes in PyPlot.jl per se.

(Note that on my machine `t = time.time(); import matplotlib.pyplot; time.time() - t` takes exactly the same time as `pyimport("matplotlib.pyplot")` in Julia, and is almost 30% of the time of `using PyPlot`, not 10%.   Maybe you were only importing `matplotlib` alone, which doesn't initialize the backend IIRC?)

**Comment by ufechner7** [comment]
Thanks that you added some more info. 
On my (desktop) machine I get the following timings:
Python:
```
In [1]: import time

In [2]: t = time.time(); import matplotlib.pyplot; time.time()-t
Out[2]: 0.16113495826721191
```
Julia:
```
julia> tic(); using PyPlot; toc()
elapsed time: 2.846236221 seconds
```
So Julia is a factor of 17.75 slower then Python. Or am I missing something?

**Comment by stevengj** [comment]
Is it the same Python?  What is the time for `using PyCall` and `pyimport("matplotlib.pyplot")` in Julia?

**Comment by ufechner7** [comment]
```
julia> tic(); using PyCall; toc()
elapsed time: 1.012015693 seconds
```
```
julia> tic(); pyimport("matplotlib.pyplot"); toc()
elapsed time: 0.162324883 seconds
```
How can I check, if it is the same Python?

**Comment by stevengj** [comment]
`PyCall.python` is the `python` executable that uses the same Python libraries.

If you add in the time for `using Colors` (another fairly big package), it sounds like your machine is similar to mine: the majority of the time to load PyPlot consists of things that are out of PyPlot's control.
