### ISSUE TITLE
LLVM error when using PyPlot on julia 0.5

### ISSUE THREAD

**Issue by bjarthur** [stevengj/PyPlot.jl#200]
```
julia> using PyPlot
INFO: Precompiling module PyPlot...
LLVM ERROR: Program used external function '_julia_getindex_23955' which could not be resolved!
```

i'm not sure what the number 23955 means, but it changes.  i've seen 23887 and 23839 as well.

**Comment by colbec** [comment]
Does the discussion at https://github.com/JuliaLang/julia/pull/15300#issuecomment-193099539 help to understand this issue?

**Comment by juliohm** [comment]
I having the same issue.

**Comment by stevengj** [comment]
This is a Julia bug, and an issue should be opened there, following up on 15300.

**Comment by bjarthur** [comment]
no longer a problem as of commit 1b4618e* on 2016-04-13.
