### ISSUE TITLE
Comportment frameon in Legend

### ISSUE THREAD

**Issue by charlesll** [stevengj/PyPlot.jl#201]
Hello, 

I was trying to remove the frame of the Legend box in my plots, and tried:

    legend(frameon="False")

This did not work... Curiously, if I do:

    legend(frameon="False")
    legend(fancybox="True")

The frame eventually disappears. Even more curiously,

    legend(fancybox="True",frameon="False")

does not work, there is still the box frame, with rounded corners as expected from the use of fancybox = "True".

I just wanted to signal such interesting behaviour, because it seems  to me that the argument frameon is not always properly read. I don't know if this is inherent to PyPlot.jl or is something affecting Matplotlib.

Best,
Charles.

**Comment by stevengj** [comment]
`False` and `True` in Python are Boolean constants, not strings.  The analogue in Julia is `false` or `true`.  e.g. this works:
```jl
using PyPlot
plot(rand(10))
legend(["ok"], frameon=false)
```
