### ISSUE TITLE
Warning with Gtk version

### ISSUE THREAD

**Issue by juliohm** [stevengj/PyPlot.jl#212]
```julia
using PyPlot
```
>sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
/usr/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "

**Comment by stevengj** [comment]
Dup of #181.
