### ISSUE TITLE
Automated matplotlib installation fails on Windows

### ISSUE THREAD

**Issue by ChrisRackauckas** [stevengj/PyPlot.jl#213]
The automated matplotlib installation fails on Windows. Fails on two of my machines and Appvoyer. Here is what the output looks like on Appvoyer: https://ci.appveyor.com/project/ChrisRackauckas/differentialequations-jl/branch/master/job/m9gc5b74ej6mafyu

(If this can't get fixed, is there another way to use matplotlib with Appvoyer?)

**Comment by stevengj** [comment]
Is this resolved?  Seems like it's passing now.

**Comment by ChrisRackauckas** [comment]
Yeah somehow it worked itself out.
