### ISSUE TITLE
Strange behavior in scatter when size is between 1e-22 and 1e-29

### ISSUE THREAD

**Issue by rodonn** [stevengj/PyPlot.jl#214]
```
using PyPlot
x = repmat(1:100, 100)
y = rand(length(x))
s = 100*exp10(-x)

scatter(x,y,s)
```

![image](https://cloud.githubusercontent.com/assets/2594443/15418503/aad88eb0-1e14-11e6-8e35-6bb8b3ac26fe.png)

The sizes of the points in the plot should be monotonically decreasing in x, which mostly happens except for the strange band when the size value is approximately 1e-25 when they reappear.

I tried reproducing the chart in python 3 and did not have the same strange results.
```
import matplotlib.pyplot as plt
import numpy as np
import random

x = np.repeat([a for a in range(1,31)], 100)
y = np.repeat(1, 3000)
s = np.exp(-x)
plt.scatter(x,y,s)

plt.show()
```

**Comment by rodonn** [comment]
I'm using 
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.8


I also reproduced it on my macbook with version
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by stevengj** [comment]
Are you using the same Matplotlib version in Python?  (Look at `PyPlot.version`).

**Comment by stevengj** [comment]
Wait, in Python, your computation is totally different from the one in Julia.  Can you do the same thing in Python and Julia?

**Comment by rodonn** [comment]
You're right, the same thing is happening in python after making the two bits of code more similar.

Looks like the bug is in Matplotlib, so I'll post the issue over there instead.

Thanks!

Python 3
![image](https://cloud.githubusercontent.com/assets/2594443/15438394/d30c15a2-1e80-11e6-9612-9029dd43be5f.png)

Julia
![image](https://cloud.githubusercontent.com/assets/2594443/15438410/df81e0e6-1e80-11e6-8792-0cdd2c5a9522.png)
