### ISSUE TITLE
Failed to precompile PyPlot on Archlinux

### ISSUE THREAD

**Issue by thomascello** [stevengj/PyPlot.jl#218]
I have the same problem as [issue 216](https://github.com/stevengj/PyPlot.jl/issues/216) but since that [Compat.jl/pull/211](https://github.com/JuliaLang/Compat.jl/pull/211) has been merge, I have a new problem when I'm trying to use PyPlot: 

`julia> using PyPlot
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/FixedPointNumbers.ji for module FixedPointNumbers.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/PyPlot.ji for module PyPlot.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/JSON.ji for module JSON.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/Conda.ji for module Conda.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/SHA.ji for module SHA.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/ColorTypes.ji for module ColorTypes.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/Colors.ji for module Colors.
INFO: Recompiling stale cache file /home/tm/.julia/lib/v0.4/LaTeXStrings.ji for module LaTeXStrings.
/usr/lib/python3.5/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
ERROR: InitError: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError('Cairo backend requires that cairocffi or pycairo is installed.',)
  File "/usr/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3agg.py", line 12, in <module>
    from .backend_cairo import cairo, HAS_CAIRO_CFFI
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_cairo.py", line 38, in <module>
    raise ImportError("Cairo backend requires that cairocffi or pycairo is installed.")

 [inlined code] from /home/tm/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/tm/.julia/v0.4/PyCall/src/PyCall.jl:340
 in __init__ at /home/tm/.julia/v0.4/PyPlot/src/PyPlot.jl:250
 in _require_from_serialized at loading.jl:84
during initialization of module PyPlot`

Thanks in advance!

**Comment by stevengj** [comment]
It seems that the real source of the error is indicated by the "Cairo backend requires that cairocffi or pycairo is installed" message.   Install pycairo and try again.  Or switch backends.

Or rebuild PyCall to use Conda (via `ENV["PYTHON"]=""; Pkg.build("PyCall")`), in which case it will auto-install its own matplotlib.

**Comment by thomascello** [comment]
Thanks a lot for your help.
Only the `ENV["PYTHON"]=""; Pkg.build("PyCall")` worked but it's working :)
