### ISSUE TITLE
PyPlot fails to precompile with the latest Julia version

### ISSUE THREAD

**Issue by asikstel** [stevengj/PyPlot.jl#222]
Hi,

using Julia version Version 0.5.0-dev+4553 (2016-06-06 02:05 UTC)
 Commit f4cb80b* (0 days old master)

with the latest PyCall and PyPlot. PyCall was built with its own python version. 
`using PyPlot `
leads to the following error

while loading /home/aleks/.julia/v0.5/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: LoadError: InitError: MethodError: no method matching |(::UInt32, ::Void)
Closest candidates are:
  |(::Any, ::Any, !Matched::Any, !Matched::Any...)
  |{T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8}}(::T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8}, !Matched::T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8})
  |(::Integer)
  ...
 in PyCall.PyTypeObject(::String, ::Int64, ::PyCall.##20#21) at /home/aleks/.julia/v0.5/PyCall/src/pytype.jl:265
 in pyjlwrap_init() at /home/aleks/.julia/v0.5/PyCall/src/pytype.jl:385
 in __init__() at /home/aleks/.julia/v0.5/PyCall/src/pyinit.jl:107
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:174
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at ./loading.jl:202
 in require(::Symbol) at ./loading.jl:332
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
during initialization of module PyCall
while loading /home/aleks/.julia/v0.5/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /home/aleks/.julia/lib/v0.5/PyPlot.ji
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:364
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

Many thanks in advance.
Aleksey

**Comment by stevengj** [comment]
This looks like an error precompiling PyCall, not PyPlot per se.
