### ISSUE TITLE
show() no longer working in non-interactive mode

### ISSUE THREAD

**Issue by mlxd** [stevengj/PyPlot.jl#225]
Since the update to v2.2.0 I can no longer use the show() function in non-interactive mode. Pinning to v2.1.1 shows that the function show() in PyPlot.jl has been removed. 

v2.1.1
 123 methods for generic function "show":
show() at /home/mlxd/.julia/v0.4/PyPlot/src/PyPlot.jl:450

v2.2.0
methods(PyPlot.show)
 122 methods for generic function "show":

Is this expected, and if so, is there a better way to use this function that is not given in the readme?

**Comment by RaulDurand** [comment]
Any update on this?

**Comment by bisraelsen** [comment]
Having the same problem...

**Comment by stevengj** [comment]
Should be fixed now, sorry about that.  A workaround until this is tagged is to call `plt[:show]()`.
