### ISSUE TITLE
PyPlot ceased to display correctly latexstrings

### ISSUE THREAD

**Issue by bahram-houchmandzadeh** [stevengj/PyPlot.jl#228]
The issue I'll detail below is restricted to PyPlot. Using matplotlib directly from PyCall works fine. The issue appeared suddenly on Julia 0.4.2 and still continues on Julia 0.4.5. Also, LatexStrings are correctly displayed in jupyter notebooks.

LatexStrings are not correctly displayed. The command
x=0:0.01:4*pi
y=sin(x)
plot(x,y)
xlabel(L"x^j+\theta_k",size=24)
ylabel(L"f(\theta)",size=24)

produces the attached figure. It is like PyPlot uses another set of fonts. Note that some characters (roman ones, index and super-scripts) are correctly displayed. The problem arises for all sizes. 
![figure_1](https://cloud.githubusercontent.com/assets/18464285/16412001/49742136-3d2a-11e6-804c-d4a3aa6bf1be.png)

**Comment by stevengj** [comment]
I can't reproduce the problem.  What version of Matplotlib are you using?  (Given by`PyPlot.version`).   What is the output of `versioninfo()`?

**Comment by bahram-houchmandzadeh** [comment]
Hi Steven,

Let me first thank you for your Julia packages (PyCall, PyPlot, ...).

The problem is indeed not very reproducible (happens on this computer, but not on the others I have). What seemed strange is that calling matplotlib from PyCall works fine, but not PyPlot. I tried to delete all caches of matplotlib to no avail. It is really like PyPlot uses another font encoding for anything outside A-Z.

Here the information you requested, but the problem occured a month ago for julia 0.4.2 and has not been improved by upgrades : 
PyPlot.version
    v"1.3.1"
versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2609 0 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by stevengj** [comment]
It is probably that PyPlot is using a different backend.  Try running `using PyCall; pyimport("matplotlib")[:get_backend]()` (after you import PyPlot or pyplot).

**Comment by bahram-houchmandzadeh** [comment]
Before submitting the issue, I had tried to change the backend in PyPlot by setting pygui(x)  where x was either  (:wx,:gtk,:gtk3,:tk,:qt,:qt_pyqt4,:qt_pyside). This did not solve the issue. However, when I compare pycall and pyplot as you suggested, there is indeed a difference. matplotlib called from pycall has "TkAgg" as backend, while matplotlib called from PyPlot can have either tk, wx or qt as backend.

If the problem is from the backend, how can I set the correct backend in PyPlot ? Obvisouly, pygui(:tkagg) or any variation on this name returns an error.

Here the output of the commands.

1- PyCall.

@pyimport matplotlib.pyplot as plt
plt.rc("text", usetex=true)
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
plt.plot(x, y, color="b", linewidth=2.0)
plt.xlabel("\$r(\\theta)\$",fontsize=16)
plt.ylabel("\$\\sum_\{i=1\}^\{i=r\} y(\\theta)\$",fontsize=16)
plt.show()

produces
![pycall_1](https://cloud.githubusercontent.com/assets/18464285/16523385/727d8b00-3fa3-11e6-8f82-a7a2f37ff771.png)

and 
pyimport("matplotlib")[:get_backend]()
produces 
"TkAgg"

2- PyPlot.
clf()
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
plot(x, y, color="b", linewidth=2.0)
xlabel(L"r(\theta)",fontsize=16)
ylabel(L"\sum_{i=1}^{i=r} y(\theta)",fontsize=16)
tight_layout()

produces 
![pyplot_1](https://cloud.githubusercontent.com/assets/18464285/16523467/e514d362-3fa3-11e6-8e38-365c4417efee.png)

and 
pygui()
produces 
:tk.

while 
using PyCall
pyimport("matplotlib")[:get_backend]()

still produces TkAgg.

**Comment by stevengj** [comment]
The symbol returned by `pygui()` is not the same as the Matplotlib backend string.   Since `get_backend` is producing `TkAgg` in both cases, it seems that is not the difference.

**Comment by KristofferC** [comment]
Looks like: https://github.com/matze/mtheme/issues/170#issuecomment-179366602.

**Comment by stevengj** [comment]
Thanks @KristofferC, seems like it was fixed upstream.
