### ISSUE TITLE
Install PyPlot/PyCall without Outlook process?

### ISSUE THREAD

**Issue by anhtecon** [stevengj/PyPlot.jl#230]
I got the following errors when installing the package PyPlot (and PyCall). Does this problem result from not having Outlook on the computer and how should I solve it? 

Thanks so much, 

```
INFO: Installing LaTeXStrings v0.1.6
INFO: Installing PyPlot v2.2.0
INFO: Building PyCall
Get-Process : Cannot find a process with the name "Outlook". Verify the process name and call the cmdlet again.
At line:1 char:1
+ Get-Process Outlook
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Outlook:String) [Get-Process],
   ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.
   Commands.GetProcessCommand

```

**Comment by stevengj** [comment]
Outlook is not required.   This is a harmless warning message from the Conda installer: it checks for Outlook because Outlook crashes the Minoconda installer program (Luthaf/Conda.jl#15).  There is an open issue to remove the warning message about not finding Outlook: Luthaf/Conda.jl#25
