### ISSUE TITLE
ERROR: LOADERROR

### ISSUE THREAD

**Issue by tobytoon** [stevengj/PyPlot.jl#231]
Hi, i just started out with Julia, and the tutorial i followed required the PyPlot library, i installed with `Pkg.add("PyPlot")` , after installing, running this code `using PyPlot` gives me error 

`/usr/bin/julia: symbol lookup error: /usr/lib/liblapack.so.3: undefined symbol: ATL_idamax
ERROR: LoadError: LoadError: Failed to precompile Colors to /home/toby/.julia/lib/v0.4/Colors.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:240
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/toby/.julia/v0.4/PyPlot/src/colormaps.jl, in expression starting on line 4
while loading /home/toby/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 409
ERROR: Failed to precompile PyPlot to /home/toby/.julia/lib/v0.4/PyPlot.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266`

**Comment by stevengj** [comment]
Looks like you are using a version of Matplotlib (or rather of Numpy) that is linked to the [ATLAS BLAS](http://math-atlas.sourceforge.net/) version of LAPACK (it is expecting the `ATL_...` symbol in liblapack), whereas Julia is normally linked to the [OpenBLAS](http://math-atlas.sourceforge.net/) version of BLAS/LAPACK.  (Or maybe vice versa: maybe your distro ships a `julia` linked to ATLAS BLAS?)  In any case, it looks like a conflict where Julia and Numpy are using two incompatible BLAS libraries?

What does `versioninfo()` print?  If you are using a weird Julia version that is linked to ATLAS BLAS, maybe you just need to download a newer version of Julia?

**Comment by tobytoon** [comment]
I've been able to resolve the issue, purged julia, removed the .julia folder... basically i restarted the whole installation process and all. Thanks
