### ISSUE TITLE
using PyPlot fails to initialize gives  ImportError('No module named version',)

### ISSUE THREAD

**Issue by nw11** [stevengj/PyPlot.jl#232]
Not sure whether this is more suitable for PyCall or PyPlot

Julia Version 0.4.2-pre+18 (2015-11-26 08:03 UTC)

I have just switched to using anaconda. 

I  rebuilt PyCall
```
ENV["PYTHON"]=""
Pkg.build("PyCall")
```

Now when I do : 

```
using PyPlot

INFO: Installing matplotlib via the Conda matplotlib package...
Fetching package metadata .......
Solving package specifications: ..........

\# All requested packages already installed.
\# packages in environment at /home/nic/.juliapkgs/v0.4/Conda/deps/usr:
\# matplotlib                1.5.1               np111py27_0  
ERROR: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named version',)
  File "/home/nic/.juliapkgs/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/home/nic/.juliapkgs/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy as np
  File "/home/nic/.juliapkgs/v0.4/Conda/deps/usr/lib/python2.7/site-packages/numpy/__init__.py", line 175, in <module>
    from .version import git_revision as __git_revision__

 [inlined code] from /home/nic/.juliapkgs/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/nic/.juliapkgs/v0.4/PyCall/src/PyCall.jl:341
 in pyimport_conda at /home/nic/.juliapkgs/v0.4/PyCall/src/PyCall.jl:432
 in __init__ at /home/nic/.juliapkgs/v0.4/PyPlot/src/PyPlot.jl:212
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
during initialization of module PyPlot
```

**Comment by stevengj** [comment]
That's odd, it looks like a problem in Matplotlib itself.  If you run the Conda Python (in `/home/nic/.juliapkgs/v0.4/Conda/deps/usr/bin/python`, I think?) can it import `matplotlib`?

**Comment by stevengj** [comment]
What does `versioninfo()` print?  Have you tried running `Pkg.update()` in case you have out-of-date packages?

**Comment by nw11** [comment]
thanks for help, yes, so the same error message comes out of the python console doing `import matplotlib`. 
```
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nic/.juliapkgs/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/home/nic/.juliapkgs/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy as np
  File "/home/nic/.juliapkgs/v0.4/Conda/deps/usr/lib/python2.7/site-packages/numpy/__init__.py", line 175, in <module>
    from .version import git_revision as __git_revision__
ImportError: No module named version
```
Updated all packages and have the same thing

Tried a few things like reinstalling Conda.jl and reinstalling matplotlib using Conda.rm/add

versioninfo()
```
Julia Version 0.4.2-pre+18
Commit eb31eef (2015-11-26 08:03 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
Seems like a problem with the Conda installation, then.   Maybe you have some environment variable set that is screwing up your Conda install?  (Type `env` in the shell and look for anything Python-related.)

cc @Luthaf

**Comment by nw11** [comment]
just to add - the only thing I can see is a BYOBU_PYTHON=python3, which I guess is set when I start byobu (screen like window manager in ubuntu). Might be something in this - a post on stackoverflow here with similar error msg http://stackoverflow.com/questions/32423793/importerror-no-module-named-version comes down to python3/2 conflict. I tried reinstalling conda.jl and matplotlib through Conda.jl - outside of byobu where this env variable doesn't exist - but doesn't seem to help. Decided to point pycall to a local anaconda python install outside of Conda.jl and all works fine there.

**Comment by stevengj** [comment]
Probably you should file Conda issue since the problem seems independent of PyPlot.
