### ISSUE TITLE
plotting order in figure

### ISSUE THREAD

**Issue by abieler** [stevengj/PyPlot.jl#236]
I want to plot 3 data sets on one figure from a jupyter notebook.
Two bar graphs first and then a scatter plot on top of this.

In the final figure the scatter plot data is hidden behind the bars, even though
I add it last. The "y3" label in the legend also appears on the top,
indicating it gets processed first?

```julia
w = 0.9
w2 = 0.4

x = 1:3
y1 = [1,2,3]
y2 = [2,2,2]
y3 = [2,3,1]

fig = plt[:figure]()
plt[:bar](x.-(w/2), y1, log=true, width=w, color="#BFBFBF", label="y1")
plt[:bar](x.-(w2/2), y2, log=true, width=w2, color="k", label="y2")
plt[:scatter](x, y3, color="orange", edgecolors="k",s=40, label="y3")
legend()
```

**Comment by tbreloff** [comment]
You can always use the zorder keyword to specify a precise ordering.

**Comment by stevengj** [comment]
Seems like an issue in the underlying matplotlib library, not with PyPlot per se?

(Note, by the way, that `figure` and `bar` and `scatter` are exported by PyPlot, so you can just type `figure()` and not `plt[:figure]()` etcetera.)
