### ISSUE TITLE
Trouble with Automating Python installation

### ISSUE THREAD

**Issue by huckl3b3rry87** [stevengj/PyPlot.jl#238]
I am a new user and I am having some difficulty getting started, when I run the commands in the Automating Python Installation, I get:

![capture2](https://cloud.githubusercontent.com/assets/8204378/17790316/e716e5a2-6563-11e6-84fc-9c2349b62e94.PNG)

 I also tried installing Python and pointing to it like this:
ENV[“PYTHON”] = “C:/Python27/python.exe”
but I also get issues and it tells me to let Conda handle it for me, but I cannot get to seem that to work.

**Comment by huckl3b3rry87** [comment]
I just fixed it. I just deleted julia and installed the packages in the correct order

**Comment by stevengj** [comment]
Glad that it is working now, I guess you were manually mucking around with the packages and screwed something up?
