### ISSUE TITLE
Plot3D function

### ISSUE THREAD

**Issue by ghost** [stevengj/PyPlot.jl#57]
When calling `plot3d` with three 1D arrays e.g. `plot3D( x,y,z )` the following error occurs:

```
PyError (PyObject_Call) <type 'exceptions.ValueError'>
ValueError(u'third arg must be a format string',)
  File "/Library/Python/2.7/site-packages/matplotlib-1.4.x-py2.7-macosx-10.9-intel.egg/mpl_toolkits/mplot3d/axes3d.py", line 1518, in plot
    lines = Axes.plot(self, xs, ys, *args[argsi:], **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib-1.4.x-py2.7-macosx-10.9-intel.egg/matplotlib/axes/_axes.py", line 1333, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/Library/Python/2.7/site-packages/matplotlib-1.4.x-py2.7-macosx-10.9-intel.egg/matplotlib/axes/_base.py", line 303, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/Library/Python/2.7/site-packages/matplotlib-1.4.x-py2.7-macosx-10.9-intel.egg/matplotlib/axes/_base.py", line 265, in _plot_args
    raise ValueError('third arg must be a format string')
```

It seems to want a call of the form `plot3D( xs,yz,*args,*kwargs )` as in the Python documentation for mplot3d [ http://matplotlib.org/dev/mpl_toolkits/mplot3d/tutorial.html ] but is this incorrect? The accompanying python example on that webpage calls using `ax.plot( x,y,z,label="parametric curve" )`

I should add, the exact call I am using is `plot3D( y[ 1,: ]', y[ 2,: ]', y[ 3,: ]' )`

**Comment by kleinash** [comment]
Hi, I am getting this error using spy(). Could you please write out the full entry?

**Comment by stevengj** [comment]
@kleinash, what code are you entering, exactly?  What happens if you enter the corresponding code in Python?

**Comment by kleinash** [comment]
@stevengj I went over to using Gadfly with spy() which is now working - but now I have a different issue - can get it running in julia, but I am having an issue with any form of ide (vim / sublime / IJulia) have tried them all.

**Comment by stevengj** [comment]
@kleinash, this issue is not a general help forum. You can try the `julia-users` mailing list if you want to ask general questions.   However, when you report a problem, you should be sure to say (a) what version of Julia you hava and what operating system you are running (b) what exact command you tried and (c) what exact error message you got.  See also [this advice](http://www.catb.org/esr/faqs/smart-questions.html).

**Comment by kleinash** [comment]
@stevengj Noted thank you.
