### ISSUE TITLE
Import PyPlot fails

### ISSUE THREAD

**Issue by ufechner7** [stevengj/PyPlot.jl#86]
Hello,

if I try to import PyPlot with julia 0.3 it fails:

julia> import PyPlot
/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1155: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
ERROR: PyError (PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named _backend_gdk',)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 98, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 28, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 33, in <module>
    from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 30, in <module>
    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array

 in pyerr_check at /home/ufechner/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /home/ufechner/.julia/v0.3/PyCall/src/PyCall.jl:85
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/ufechner/.julia/v0.3/PyPlot/src/PyPlot.jl, in expression starting on line 108

julia> 
Error message:
ImportError('No module named _backend_gdk',)

This is on Ubuntu 12.04, 64 bit, using Julia "Version 0.3.0 (2014-08-20 20:43 UTC)"
with matplotlib 1.3.1 and numpy 1.8.1

Plotting works, if I use PyCall directly:

using PyCall
@pyimport numpy
@pyimport pylab
 x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
pylab.plot(x, y; color="red", linewidth=2.0, linestyle="--")
pylab.show()

Any idea?

**Comment by stevengj** [comment]
See also #110

**Comment by stevengj** [comment]
GTK3 support should be fixed by bb24ff8b8f716845094a0622a46c57960b392a45 ... @ufechner7, please try it and let me know.

**Comment by ufechner7** [comment]
It is working now for me. Thank's for the fix! 
Uwe
