### ISSUE TITLE
plot_surface and facecolors

### ISSUE THREAD

**Issue by mardukbp** [stevengj/PyPlot.jl#91]
Apparently, the `cmap` keyword in `plot_surface` colors the surface in the Z direction. I needed to color the surface of a sphere with a scalar function. This is achieved with the `facecolors` keyword. In Matplotlib [this is the solution](http://stackoverflow.com/questions/25023075/normalizing-colormap-used-by-facecolors-in-matplotlib):

``` python
norm = matplotlib.colors.Normalize()
ax.plot_surface(x, y, z,  rstride=1, cstride=1, facecolors=cm.jet(norm(colorfunction)))
```

However, in `PyPlot.jl` the `ColorMap` type does not have a method that takes an array of floats and returns the associated colors in the colormap. The workaround is

``` julia
map = get_cmap("Blues")
map[:__call__](linspace(0,1,10))
```

Something similar happens with `matplotlib.colors.Normalize`. As a result, in `PyPlot.jl` the `facecolors` keyword must have the value

``` julia
facecolors=map[:__call__](matplotlib.colors.Normalize()[:__call__](colorfunction))
```

I am new to Julia and don't have the skills (yet) to submit a pull request fixing this. Hopefully it won't be difficult to implement.

**Comment by gozzilli** [comment]
Finding this saved my life. I spent hours trying to get the colormap to work, and couldn't figure out how to use it. Could this be added to the documentation, or to this [recordnotfound](http://recordnotfound.com/PyPlot-jl-stevengj-3407) page, which has the most amount of detail on colormaps, or to the [README](https://github.com/stevengj/PyPlot.jl) of this project? Thanks!

**Comment by stevengj** [comment]
@gozzilli, in Julia 0.4 the `__call__` should no longer be needed, because call overloading works.

**Comment by IlyaOrson** [comment]
Hello,
I was trying to emulate this [examples](http://stackoverflow.com/questions/8931268/using-colormaps-to-set-color-of-line-in-matplotlib)  with julia 0.4.5 and matplotlib 1.5.1 and I couldn't avoid the use of `__call__` to get them working.

For example, I used this:

```
number_of_lines = 5
viri = get_cmap("viridis")
cm_subsection = linspace(0.0, 1.0, number_of_lines)
colors = [viri[:__call__](x) for x in cm_subsection]
for col in colors
       plot(rand(10), color = col)
end
```
because a direct call throws an error:

`colors = [viri(x) for x in cm_subsection]`

> ERROR: MethodError: `call` has no method matching call(::PyPlot.ColorMap, ::Float64)
> Closest candidates are:
>   BoundsError()
>   BoundsError(::Any...)
>   DivideError()
>   ...
>  in anonymous at no file

I get a similar error for the suggestion made [here](https://groups.google.com/forum/#!searchin/julia-users/color$20pyplot/julia-users/C3l5bEc8_eg/J-E5grjKTYIJ).
Am I missing something?
Thanks

**Comment by stevengj** [comment]
I can't reproduce:
```jl
julia> using PyPlot; c = get_cmap("RdBu")
ColorMap "RdBu"

julia> c(0.5)
(0.9657054999295402,0.9672433698878569,0.968089198364931,1.0)

julia> [c(x) for x in linspace(0,1,10)]
10-element Array{Any,1}:
 (0.40392157435417175,0.0,0.12156862765550613,1.0)               
 (0.711880063309389,0.12179931034060085,0.1816993519371631,1.0)  
 (0.8622837452327504,0.4295271150037354,0.3427143558567646,1.0)  
 (0.9686274528503418,0.7176470756530762,0.6000000238418579,1.0)  
 (0.9820069214876961,0.9061899325426888,0.861591703751508,1.0)   
 (0.8838908181470984,0.928489046938279,0.9530180727734285,1.0)   
 (0.6549019813537598,0.814379096031189,0.8941176533699036,1.0)   
 (0.3234909813778073,0.6149173624375287,0.7854671408148373,1.0)  
 (0.14248366800009035,0.4173010459133223,0.6833525755826164,1.0) 
 (0.019607843831181526,0.1882352977991104,0.3803921639919281,1.0)
```

**Comment by stevengj** [comment]
Maybe you need a `Pkg.update()`?

**Comment by IlyaOrson** [comment]
`Pkg.checkout("PyPlot")` did the trick. Thanks!
